#!groovy

def getEnvFromBranch(branch){
  if(branch == 'staging'){
    return 'staging'
  } else if(branch == 'master'){
    return 'production'
  } else {
    return 'testing'
  }
}

def dockerImage = ''
//def upstreamBuildCause = currentBuild.getBuildCauses('hudson.model.Cause$UpstreamCause')

pipeline {
  environment{
    ENV = getEnvFromBranch(branch)
  }
  agent {
    label 'docker'
  }
  triggers {
    upstream(upstreamProjects: "noisepage-test-performance-storage-service/test", threshold: hudson.model.Result.SUCCESS)
  }
  stages{
    stage('Checkout'){
      when {
        anyOf {
          allOf {
            triggeredBy "UpstreamCause"
            branch "test"
          }
          branch "staging"
          branch "master"
        }
      }
      steps{
        checkout scm
      }
    }
    stage('Install Deployment Dependencies') {
      when {
        anyOf {
          allOf {
            triggeredBy "UpstreamCause"
            branch "test"
          }
          branch "staging"
          branch "master"
        }
      }
      steps {
        sh "sudo apt-add-repository ppa:ansible/ansible"
        sh "sudo apt-get -y install ansible"
      }
    }
    stage('Create Namespaces') {
      when {
        anyOf {
          allOf {
            triggeredBy "UpstreamCause"
            branch "test"
          }
          branch "staging"
          branch "master"
        }
      }
      steps {
        dir('deployments'){
          script{
            sh "curl http://incrudibles-testing.db.pdl.cmu.edu/sqlsmith/results/test.txt"
            withCredentials([usernameColonPassword(credentialsId: 'jenkins_k8s', variable: 'ANSIBLE_SSH')]) {
              sh "ansible-playbook -i inventory playbooks/create-namespaces.yml -e \"env=${env.ENV} jenkins_ansible_key=${ANSIBLE_SSH}\" -vvvv"
            }
          }
        }
      }
    }
    stage ('Deploy Apps'){
      when {
        anyOf {
          allOf {
            triggeredBy "UpstreamCause"
            branch "test"
          }
          branch "staging"
          branch "master"
        }
      }
      parallel {
        stage('Performance Storage Service') {
          steps{
            dir('deployments'){
              withCredentials([usernameColonPassword(credentialsId: 'jenkins_k8s', variable: 'ANSIBLE_SSH')]) {
                sh "ansible-playbook -i inventory playbooks/pss-deployment.yml -e \"env=${env.ENV} jenkins_ansible_key=${env.ANSIBLE_SSH}\" -vvvvv"
              }
            }
          }
        }
      }
    }
  }
  post {
    cleanup{
      echo "deleting directory"
      deleteDir()
    }
  }
}
