---
kind: Service
apiVersion: v1
metadata:
  name: performance-service
  namespace: performance
spec:
  type: NodePort
  selector:
    app: pss
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http
    nodePort: 30001
  externalTrafficPolicy: Cluster
  selector:
    app: pss
