---
kind: Service
apiVersion: v1
metadata:
  name: performance-service
  namespace: performance
  labels:
    app: pss
spec:
  type: NodePort
  selector:
    app: pss
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30001
  externalTrafficPolicy: Local
