---
kind: Service
apiVersion: v1
metadata:
  name: performance-service
  namespace: "performance-{{ env }}"
  labels:
    app: pss
spec:
  type: NodePort
  selector:
    app: pss
  ports:
    - protocol: TCP
      port: 8080
      nodePort: {{ service_port | int }}
  externalTrafficPolicy: Local
