---
kind: Service
apiVersion: v1
metadata:
  name: performance-service
  #namespace: "all-performance"
  labels:
    app: pss
    #env: "{{ env }}"
spec:
  type: NodePort
  selector:
    app: pss
    ##env: "{{ env }}"
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 31000
  externalTrafficPolicy: Cluster
