---
    
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-blackbox-exporter-conf
  labels:
    app: prometheus-blackbox-exporter-conf
  namespace: monitoring
data:
  blackbox.yaml: |
    modules:
      http_2xx:
        http:
          no_follow_redirects: false
          preferred_ip_protocol: ip4
          valid_http_versions:
          - HTTP/1.1
          - HTTP/2.0
          valid_status_codes: []
        prober: http
        timeout: 5s