# Generated by Django 3.0.6 on 2020-07-23 07:55

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OLTPBenchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('query_mode', models.CharField(choices=[('simple', 'simple'), ('extended', 'extended')], max_length=30)),
                ('jenkins_job_id', models.CharField(max_length=15)),
                ('git_branch', models.CharField(max_length=255)),
                ('git_commit_id', models.CharField(max_length=40)),
                ('db_version', models.CharField(max_length=255)),
                ('environment', django.contrib.postgres.fields.jsonb.JSONField()),
                ('benchmark_type', models.CharField(max_length=20)),
                ('scale_factor', models.DecimalField(decimal_places=4, max_digits=10)),
                ('terminals', models.PositiveSmallIntegerField()),
                ('client_time', models.PositiveSmallIntegerField()),
                ('weights', django.contrib.postgres.fields.jsonb.JSONField()),
                ('metrics', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('incremental_metrics', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'oltpbench_results',
            },
        ),
    ]
