# Generated by Django 3.0.6 on 2020-07-22 06:22

from django.db import migrations
from django.contrib.auth.models import User
from ...settings.utils import get_environ_value

def add_user(apps, schema_editor):
    try:
        user = User.objects.create_user(username=get_environ_value('PSS_CREATOR_USER'), password=get_environ_value('PSS_CREATOR_PASSWORD'))
        user.save()
    except:
        msg = 'Migration error: create user failed'
        print(msg) 

def remove_user(apps,schema_editor):
    try:
        user = User.objects.get(username=get_environ_value('PSS_CREATOR_USER'))
        user.delete()
    except:
        msg = 'Migration error: delete user failed'
        print(msg)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_user, remove_user),
    ]
