# Generated by Django 3.0.6 on 2020-07-24 05:44

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oltpbenchresult',
            name='incremental_metrics',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
