# Generated by Django 3.0.6 on 2020-08-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200724_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='oltpbenchresult',
            name='max_connection_threads',
            field=models.PositiveSmallIntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oltpbenchresult',
            name='wal_device',
            field=models.CharField(choices=[('RAM disk', 'RAM disk'), ('HDD', 'HDD'), ('SATA SSD', 'SATA SSD'), ('NVMe SSD', 'NVMe SSD'),('None','None')], default='HDD', max_length=30),
            preserve_default=False,
        ),
    ]
