# Generated by Django 3.0.6 on 2020-08-01 02:30

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200724_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oltpbenchresult',
            name='weights',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
