# Generated by Django 3.0.6 on 2020-09-15 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200731_2230'),
        ('api', '0004_auto_20200811_1313'),
    ]

    operations = [
    ]
