# Generated by Django 3.0.6 on 2020-09-27 18:35

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20200915_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrobenchmarkResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('query_mode', models.CharField(choices=[('simple', 'simple'), ('extended', 'extended')], max_length=30)),
                ('jenkins_job_id', models.CharField(max_length=15)),
                ('git_branch', models.CharField(max_length=255)),
                ('git_commit_id', models.CharField(max_length=40)),
                ('db_version', models.CharField(max_length=255)),
                ('environment', django.contrib.postgres.fields.jsonb.JSONField()),
                ('benchmark_suite', models.CharField(max_length=255)),
                ('benchmark_name', models.CharField(max_length=255)),
                ('threads', models.PositiveSmallIntegerField()),
                ('min_runtime', models.PositiveIntegerField()),
                ('wal_device', models.CharField(choices=[('RAM disk', 'RAM disk'), ('HDD', 'HDD'), ('SATA SSD', 'SATA SSD'), ('NVMe SSD', 'NVMe SSD'), ('None', 'None')], max_length=30)),
                ('metrics', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'microbenchmark_results',
            },
        ),
    ]
