# Generated by Django 3.0.6 on 2020-10-12 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_microbenchmarkresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microbenchmarkresult',
            name='query_mode',
        ),
    ]
