# Generated by Django 3.0.6 on 2020-10-30 18:26

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_microbenchmarkresult_query_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryMetricsResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('jenkins_job_id', models.CharField(max_length=15)),
                ('git_branch', models.CharField(max_length=255)),
                ('git_commit_id', models.CharField(max_length=40)),
                ('db_version', models.CharField(max_length=255)),
                ('environment', django.contrib.postgres.fields.jsonb.JSONField()),
                ('metrics', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'binary_metrics_results',
            },
        ),
    ]
