# Generated by Django 3.1.2 on 2020-11-01 07:05

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_binarymetricsresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binarymetricsresult',
            name='environment',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='binarymetricsresult',
            name='metrics',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='microbenchmarkresult',
            name='environment',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='microbenchmarkresult',
            name='metrics',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='oltpbenchresult',
            name='environment',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='oltpbenchresult',
            name='incremental_metrics',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='oltpbenchresult',
            name='metrics',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='oltpbenchresult',
            name='weights',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.RenameModel(
            old_name='BinaryMetricsResult',
            new_name='ArtifactStatsResult',
        ),
        migrations.AlterModelTable(
            name='artifactstatsresult',
            table='artifact_stats_results',
        ),
    ]
