# Generated by Django 3.0.6 on 2020-11-09 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_binarymetricsresult'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BinaryMetricsResult',
            new_name='ArtifactStatsResult',
        ),
        migrations.AlterModelTable(
            name='artifactstatsresult',
            table='artifact_stats_results',
        ),
    ]