# Generated by Django 3.1.2 on 2020-11-22 03:24

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201109_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifactstatsresult',
            name='environment',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='artifactstatsresult',
            name='metrics',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='microbenchmarkresult',
            name='environment',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='microbenchmarkresult',
            name='metrics',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='oltpbenchresult',
            name='environment',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='oltpbenchresult',
            name='incremental_metrics',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='oltpbenchresult',
            name='metrics',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='oltpbenchresult',
            name='weights',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
