# Generated by Django 3.1.2 on 2021-01-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201121_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifactstatsresult',
            name='id',
        ),
        migrations.RemoveField(
            model_name='microbenchmarkresult',
            name='id',
        ),
        migrations.RemoveField(
            model_name='oltpbenchresult',
            name='id',
        ),
        migrations.AlterField(
            model_name='artifactstatsresult',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='microbenchmarkresult',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='oltpbenchresult',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
