{
 "title": "Testing Metrics",
 "time": { "from": "now", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Uptime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Performance Storage Service",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{pod=~\"testing-performance-storage-service.*\",container=\"performance-storage-service\"}"
    }
   ]
  },
  {
   "title": "Grafana",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{pod=~\"testing-grafana.*\",container=\"grafana\"}"
    }
   ]
  },
  {
   "title": "TimeScaleDB",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{pod=~\"testing-timescaledb.*\",container=\"timescaledb\"}"
    }
   ]
  }
 ]
}