{
 "title": "Overall",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "TPC-C",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "throughput" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 1\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_oltpbench_result\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'tpcc' AND\n  terminals = '1'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 2\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_oltpbench_result\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'tpcc' AND\n  terminals = '2'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 4\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_oltpbench_result\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'tpcc' AND\n  terminals = '4'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 8\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_oltpbench_result\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'tpcc' AND\n  terminals = '8'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 16\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_oltpbench_result\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'tpcc' AND\n  terminals = '16'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "TATP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "throughput" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 1\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_oltpbench_result\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'tatp' AND\n  terminals = '1'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 2\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_oltpbench_result\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'tatp' AND\n  terminals = '2'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 4\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_oltpbench_result\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'tatp' AND\n  terminals = '4'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 8\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_oltpbench_result\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'tatp' AND\n  terminals = '8'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 16\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_oltpbench_result\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'tatp' AND\n  terminals = '16'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "NOOP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "throughput" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 1\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_oltpbench_result\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'noop' AND\n  terminals = '1'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 2\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_oltpbench_result\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'noop' AND\n  terminals = '2'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 4\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_oltpbench_result\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'noop' AND\n  terminals = '4'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 8\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_oltpbench_result\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'noop' AND\n  terminals = '8'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 16\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_oltpbench_result\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'noop' AND\n  terminals = '16'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "SmallBank",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "throughput" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 1\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_oltpbench_result\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'smallbank' AND\n  terminals = '1'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 2\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_oltpbench_result\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'smallbank' AND\n  terminals = '2'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 4\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_oltpbench_result\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'smallbank' AND\n  terminals = '4'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 8\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_oltpbench_result\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'smallbank' AND\n  terminals = '8'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 16\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_oltpbench_result\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'smallbank' AND\n  terminals = '16'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "YCSB",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "throughput" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 1\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_oltpbench_result\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'ycsb' AND\n  terminals = '1'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 2\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_oltpbench_result\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'ycsb' AND\n  terminals = '2'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 4\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_oltpbench_result\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'ycsb' AND\n  terminals = '4'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 8\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_oltpbench_result\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'ycsb' AND\n  terminals = '8'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 16\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_oltpbench_result\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'ycsb' AND\n  terminals = '16'\nORDER BY 1"
    }
   ]
  }
 ]
}