{
 "title": "Scalability",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 22, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  git_commit_id\nFROM test_table\nWHERE\n  $__timeFilter(\"time\") AND\n   benchmark_type = 'tatp'\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Commit ID",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  git_commit_id\nFROM test_table\nWHERE\n  $__timeFilter(\"time\") AND\n   benchmark_type = 'tatp'\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "TATP",
   "type": "graph",
   "description": "This is the last Benchmark result recorded for TATP in the time range selected.",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "Throughput (rps)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n   time,\n   CAST(terminals AS TEXT) as metric,\n   CAST(result->>'throughput' AS DOUBLE PRECISION) as value\nFROM test_table\nWHERE\n   $__timeFilter(time) AND\n   benchmark_type = 'tatp'\nGROUP BY time, benchmark_type, terminals, result->>'throughput'\nORDER BY terminals, time"
    }
   ]
  },
  {
   "title": "NOOP",
   "type": "graph",
   "description": "This is the last Benchmark result recorded for NOOP in the time range selected.",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "Throughput (rps)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n   time,\n   CAST(terminals AS TEXT) as metric,\n   CAST(result->>'throughput' AS DOUBLE PRECISION) as value\nFROM test_table\nWHERE\n   $__timeFilter(time) AND\n   benchmark_type = 'noop'\nGROUP BY time, benchmark_type, terminals, result->>'throughput'\nORDER BY terminals, time"
    }
   ]
  },
  {
   "title": "YCSB",
   "type": "graph",
   "description": "This is the last Benchmark result recorded for YCSB in the time range selected.",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "Throughput (rps)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n   time,\n   CAST(terminals AS TEXT) as metric,\n   CAST(result->>'throughput' AS DOUBLE PRECISION) as value\nFROM test_table\nWHERE\n   $__timeFilter(time) AND\n   benchmark_type = 'ycsb'\nGROUP BY time, benchmark_type, terminals, result->>'throughput'\nORDER BY terminals, time"
    }
   ]
  },
  {
   "title": "SMALLBANK",
   "type": "graph",
   "description": "This is the last Benchmark result recorded for SMALLBANK in the time range selected.",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "Throughput (rps)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n   time,\n   CAST(terminals AS TEXT) as metric,\n   CAST(result->>'throughput' AS DOUBLE PRECISION) as value\nFROM test_table\nWHERE\n   $__timeFilter(time) AND\n   benchmark_type = 'smallbank'\nGROUP BY time, benchmark_type, terminals, result->>'throughput'\nORDER BY terminals, time"
    }
   ]
  },
  {
   "title": "TPC-C",
   "type": "graph",
   "description": "This is the last Benchmark result recorded for TPC-C in the time range selected.",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "Throughput (rps)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n   time,\n   CAST(terminals AS TEXT) as metric,\n   CAST(result->>'throughput' AS DOUBLE PRECISION) as value\nFROM test_table\nWHERE\n   $__timeFilter(time) AND\n   benchmark_type = 'tpcc'\nGROUP BY time, benchmark_type, terminals, result->>'throughput'\nORDER BY terminals, time"
    }
   ]
  }
 ]
}