{
 "title": "Overview",
 "description": "Summarize the results from different performance metrics",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "wal_device",
    "label": "WAL device",
    "query": "SELECT DISTINCT wal_device FROM oltpbench_results"
   },
   {
    "name": "terminals",
    "query": "SELECT terminals FROM oltpbench_results"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "content": "\n# Overview\n\nThis dashboard display an overview of how NoisePage's performance changes over time \nYou can check the average throughput or latency percentage changes of all benchmarks. The blue line indicates when there is a new commit comes to master branch.\n\nFeel free to mix and match, but be warnedthe charts can get overwhelming pretty fast.\n\n\n\n"
  },
  { "title": "Throughput Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Throughput ",
   "type": "graph",
   "description": "The average throughput percentage changes of all benchmarks, compared to start date of selected time range. To change time range,  click button on top right of page. **Throughput Trends** for more details.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Throughput (tps)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \r\n\tdate AS \"time\",\r\n\tAVG(daily_benchmark_avg.avg_benchmark_change) * 100 AS \"avg throughput change per benchmark type\"\r\nFROM (\r\n\tSELECT\r\n\t  date,\r\n\t  benchmark_type,\r\n\t  AVG(benchmark_change.change) AS \"avg_benchmark_change\"\r\n\tFROM (\r\n\t  SELECT\r\n\t\t  time,\r\n\t\t  DATE(time) as \"date\",\r\n\t\t  ((metrics->>'throughput')::numeric - \r\n\t\t    FIRST_VALUE((metrics->>'throughput')::numeric) OVER(PARTITION BY benchmark_type,terminals order by time ASC)) /\r\n\t\t    FIRST_VALUE((metrics->>'throughput')::numeric) OVER(PARTITION BY benchmark_type,terminals order by time ASC) as \"change\",\r\n\t\t  terminals,\r\n\t\t  benchmark_type\r\n\t  FROM oltpbench_results\r\n\t  WHERE\r\n\t\t  $__timeFilter(\"time\") AND\r\n \t\t  query_mode = 'extended' AND\r\n  \t\tclient_time = 60 AND\r\n  \t\tgit_branch = 'origin/master' AND\r\n  \t\twal_device = '$wal_device' AND\r\n  \t\tmax_connection_threads = 32\r\n\t  ORDER BY time DESC\r\n\t) AS benchmark_change\r\n\tGROUP BY benchmark_type, date\r\n\tORDER BY date DESC\r\n) as daily_benchmark_avg\r\nGROUP BY date\r\nORDER BY date"
    }
   ]
  },
  {
   "title": "Change since last 30 days",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n\tNOW() + CONCAT(day::text,' day')::interval - '30 day'::interval as \"time\",\n\tAVG(daily_benchmark_avg.avg_benchmark_change) * 100 AS \"avg throughput change per benchmark type\"\nFROM (\n\tSELECT\n    day AS \"day\",\n    benchmark_type,\n    AVG(benchmark_change.change) AS \"avg_benchmark_change\"\n\tFROM (\n\t  SELECT\n      time,\n      (DATE(time) - DATE(NOW() - '30 day'::interval)) as \"day\",\n      ((metrics->>'throughput')::numeric - \n      FIRST_VALUE((metrics->>'throughput')::numeric) OVER(PARTITION BY benchmark_type,terminals order by time ASC)) /\n      FIRST_VALUE((metrics->>'throughput')::numeric) OVER(PARTITION BY benchmark_type,terminals order by time ASC) as \"change\",\n      terminals,\n      benchmark_type\n\t  FROM oltpbench_results\n\t  WHERE\n \t\tquery_mode = 'extended' AND\n  \t\tclient_time = 60 AND\n  \t\tgit_branch = 'origin/master' AND\n  \t\twal_device = '$wal_device' AND\n  \t\tmax_connection_threads = 32 AND\n  \t\ttime >= NOW() - '30 day'::interval\n\t  ORDER BY time DESC\n\t) AS benchmark_change\n\tGROUP BY benchmark_type, day\n\tORDER BY day DESC\n) as daily_benchmark_avg\nGROUP BY day\nORDER BY day"
    }
   ]
  },
  {
   "title": "Change since last 90 days",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n\tNOW() + CONCAT(day::text,' day')::interval - '90 day'::interval as \"time\",\n\tAVG(daily_benchmark_avg.avg_benchmark_change) * 100 AS \"avg throughput change per benchmark type\"\nFROM (\n\tSELECT\n    day AS \"day\",\n    benchmark_type,\n    AVG(benchmark_change.change) AS \"avg_benchmark_change\"\n\tFROM (\n\t  SELECT\n      time,\n      (DATE(time) - DATE(NOW() - '90 day'::interval)) as \"day\",\n      ((metrics->>'throughput')::numeric - \n      FIRST_VALUE((metrics->>'throughput')::numeric) OVER(PARTITION BY benchmark_type,terminals order by time ASC)) /\n      FIRST_VALUE((metrics->>'throughput')::numeric) OVER(PARTITION BY benchmark_type,terminals order by time ASC) as \"change\",\n      terminals,\n      benchmark_type\n\t  FROM oltpbench_results\n\t  WHERE\n \t\tquery_mode = 'extended' AND\n  \t\tclient_time = 60 AND\n  \t\tgit_branch = 'origin/master' AND\n  \t\twal_device = '$wal_device' AND\n  \t\tmax_connection_threads = 32 AND\n  \t\ttime >= NOW() - '90 day'::interval\n\t  ORDER BY time DESC\n\t) AS benchmark_change\n\tGROUP BY benchmark_type, day\n\tORDER BY day DESC\n) as daily_benchmark_avg\nGROUP BY day\nORDER BY day"
    }
   ]
  },
  {
   "title": "Change since genesis",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n\tNOW() + CONCAT(day::text,' day')::interval - (NOW() - genesis) as \"time\",\n\tAVG(daily_benchmark_avg.avg_benchmark_change) * 100 AS \"avg throughput change per benchmark type\"\nFROM (\n\tSELECT\n\t  genesis,\n    day AS \"day\",\n    benchmark_type,\n    AVG(benchmark_change.change) AS \"avg_benchmark_change\"\n\tFROM (\n\t  SELECT\n      time,\n      genesis.start AS \"genesis\",\n      (DATE(time) - DATE(genesis.start)) AS \"day\",\n      ((metrics->>'throughput')::numeric - \n      FIRST_VALUE((metrics->>'throughput')::numeric) OVER(PARTITION BY benchmark_type,terminals order by time ASC)) /\n      FIRST_VALUE((metrics->>'throughput')::numeric) OVER(PARTITION BY benchmark_type,terminals order by time ASC) as \"change\",\n      terminals,\n      benchmark_type\n\t  FROM oltpbench_results, (\n\t    SELECT time AS \"start\"\n\t    FROM oltpbench_results \n\t    ORDER BY time ASC \n\t    LIMIT 1\n\t    ) AS \"genesis\"\n\t  WHERE\n \t\tquery_mode = 'extended' AND\n  \t\tclient_time = 60 AND\n  \t\tgit_branch = 'origin/master' AND\n  \t\twal_device = '$wal_device' AND\n  \t\tmax_connection_threads = 32\n\t  ORDER BY time DESC\n\t) AS benchmark_change\n\tGROUP BY benchmark_type, day, genesis\n\tORDER BY day DESC\n) as daily_benchmark_avg\nGROUP BY day, genesis\nORDER BY day, genesis"
    }
   ]
  },
  { "title": "Latency Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Latency",
   "type": "graph",
   "description": "The average latency percentage changes of all benchmarks, compared to start date of selected time range. To change time range, click button on top right of page. See **Latency Trends** for more details.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Latency (ms)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n\tdate AS \"time\",\n\tAVG(daily_benchmark_avg.avg_benchmark_change) * 100 AS \"avg latency change per benchmark type\"\nFROM (\n\tSELECT\n\t  date,\n\t  benchmark_type,\n\t  AVG(benchmark_change.change) AS \"avg_benchmark_change\"\n\tFROM (\n\t  SELECT\n\t\t  time,\n\t\t  DATE(time) as \"date\",\n\t\t  ((metrics->'latency'->>'avg')::numeric - \n\t\t    FIRST_VALUE((metrics->'latency'->>'avg')::numeric) OVER(PARTITION BY benchmark_type,terminals order by time ASC)) /\n\t\t    FIRST_VALUE((metrics->'latency'->>'avg')::numeric) OVER(PARTITION BY benchmark_type,terminals order by time ASC) as \"change\",\n\t\t  terminals,\n\t\t  benchmark_type\n\t  FROM oltpbench_results\n\t  WHERE\n\t\t  $__timeFilter(\"time\") AND\n \t\t  query_mode = 'extended' AND\n  \t\tclient_time = 60 AND\n  \t\tgit_branch = 'origin/master' AND\n  \t\twal_device = '$wal_device' AND\n  \t\tmax_connection_threads = 32\n\t  ORDER BY time DESC\n\t) AS benchmark_change\n\tGROUP BY benchmark_type, date\n\tORDER BY date DESC\n) as daily_benchmark_avg\nGROUP BY date\nORDER BY date"
    }
   ]
  },
  {
   "title": "Change since last 30 days",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n\tNOW() + CONCAT(day::text,' day')::interval - '30 day'::interval as \"time\",\n\tAVG(daily_benchmark_avg.avg_benchmark_change) * 100 AS \"avg latency change per benchmark type\"\nFROM (\n\tSELECT\n    day AS \"day\",\n    benchmark_type,\n    AVG(benchmark_change.change) AS \"avg_benchmark_change\"\n\tFROM (\n\t  SELECT\n      time,\n      (DATE(time) - DATE(NOW() - '30 day'::interval)) as \"day\",\n      ((metrics->'latency'->>'avg')::numeric - \n\t\t    FIRST_VALUE((metrics->'latency'->>'avg')::numeric) OVER(PARTITION BY benchmark_type,terminals order by time ASC)) /\n\t\t    FIRST_VALUE((metrics->'latency'->>'avg')::numeric) OVER(PARTITION BY benchmark_type,terminals order by time ASC) as \"change\",\n      terminals,\n      benchmark_type\n\t  FROM oltpbench_results\n\t  WHERE\n \t\tquery_mode = 'extended' AND\n  \t\tclient_time = 60 AND\n  \t\tgit_branch = 'origin/master' AND\n  \t\twal_device = '$wal_device' AND\n  \t\tmax_connection_threads = 32 AND\n  \t\ttime >= NOW() - '30 day'::interval\n\t  ORDER BY time DESC\n\t) AS benchmark_change\n\tGROUP BY benchmark_type, day\n\tORDER BY day DESC\n) as daily_benchmark_avg\nGROUP BY day\nORDER BY day"
    }
   ]
  },
  {
   "title": "Change since last 90 days",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n\tNOW() + CONCAT(day::text,' day')::interval - '90 day'::interval as \"time\",\n\tAVG(daily_benchmark_avg.avg_benchmark_change) * 100 AS \"avg throughput change per benchmark type\"\nFROM (\n\tSELECT\n    day AS \"day\",\n    benchmark_type,\n    AVG(benchmark_change.change) AS \"avg_benchmark_change\"\n\tFROM (\n\t  SELECT\n      time,\n      (DATE(time) - DATE(NOW() - '90 day'::interval)) as \"day\",\n      ((metrics->'latency'->>'avg')::numeric - \n\t\t    FIRST_VALUE((metrics->'latency'->>'avg')::numeric) OVER(PARTITION BY benchmark_type,terminals order by time ASC)) /\n\t\t    FIRST_VALUE((metrics->'latency'->>'avg')::numeric) OVER(PARTITION BY benchmark_type,terminals order by time ASC) as \"change\",\n      terminals,\n      benchmark_type\n\t  FROM oltpbench_results\n\t  WHERE\n \t\tquery_mode = 'extended' AND\n  \t\tclient_time = 60 AND\n  \t\tgit_branch = 'origin/master' AND\n  \t\twal_device = '$wal_device' AND\n  \t\tmax_connection_threads = 32 AND\n  \t\ttime >= NOW() - '90 day'::interval\n\t  ORDER BY time DESC\n\t) AS benchmark_change\n\tGROUP BY benchmark_type, day\n\tORDER BY day DESC\n) as daily_benchmark_avg\nGROUP BY day\nORDER BY day"
    }
   ]
  },
  {
   "title": "Change since genesis",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n\tNOW() + CONCAT(day::text,' day')::interval - (NOW() - genesis) as \"time\",\n\tAVG(daily_benchmark_avg.avg_benchmark_change) * 100 AS \"avg throughput change per benchmark type\"\nFROM (\n\tSELECT\n\t  genesis,\n    day AS \"day\",\n    benchmark_type,\n    AVG(benchmark_change.change) AS \"avg_benchmark_change\"\n\tFROM (\n\t  SELECT\n      time,\n      genesis.start AS \"genesis\",\n      (DATE(time) - DATE(genesis.start)) AS \"day\",\n      ((metrics->'latency'->>'avg')::numeric - \n\t\t    FIRST_VALUE((metrics->'latency'->>'avg')::numeric) OVER(PARTITION BY benchmark_type,terminals order by time ASC)) /\n\t\t    FIRST_VALUE((metrics->'latency'->>'avg')::numeric) OVER(PARTITION BY benchmark_type,terminals order by time ASC) as \"change\",\n      terminals,\n      benchmark_type\n\t  FROM oltpbench_results, (\n\t    SELECT time AS \"start\"\n\t    FROM oltpbench_results \n\t    ORDER BY time ASC \n\t    LIMIT 1\n\t    ) AS \"genesis\"\n\t  WHERE\n \t\tquery_mode = 'extended' AND\n  \t\tclient_time = 60 AND\n  \t\tgit_branch = 'origin/master' AND\n  \t\twal_device = '$wal_device' AND\n  \t\tmax_connection_threads = 32\n\t  ORDER BY time DESC\n\t) AS benchmark_change\n\tGROUP BY benchmark_type, day, genesis\n\tORDER BY day DESC\n) as daily_benchmark_avg\nGROUP BY day, genesis\nORDER BY day, genesis"
    }
   ]
  },
  { "title": "Scalability Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 43 },
   "content": "This chart shows how the system scales with more client terminals. \nFor each benchmark type we calculate the expected throughput based on linear scaling.\nWe take the throughput for the benchmark run with 1 terminal and \nmultiply it by the number of terminals that was used in that test execution.\nNext we calculate the percent difference between the actual throughput and expected throughput.\nFinally, this chart shows the average percent difference across all benchmark types.\n\n\n"
  },
  {
   "title": "Average Difference Between Actual and Expected Throughput Scaling",
   "type": "graph",
   "description": "See **Scalability Details** for more details.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "percentunit", "label": "Actual and Expected TPS % Diff" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n\tMAX(time) as time,\n\tterminals::text as metric,\n\tAVG((actual_tps - expected_tps) / expected_tps) as value\nFROM (\nSELECT\n\tall_terminal_benchmarks.time,\n\tall_terminal_benchmarks.benchmark_type,\n\tall_terminal_benchmarks.terminals,\n\t(one_terminal_benchmarks.throughput * all_terminal_benchmarks.terminals) AS expected_tps,\n\t(all_terminal_benchmarks.throughput)::float AS actual_tps\nFROM (\n\tSELECT DISTINCT ON (benchmark_type)\n\t\ttime,\n\t\tbenchmark_type,\n\t\tterminals,\n\t\t(metrics->>'throughput')::float AS throughput\n\tFROM oltpbench_results\n\tWHERE\n\t\t$__timeFilter(\"time\") AND\n\t\tterminals = 1 AND\n\t\tclient_time = 60 AND\n\t\tgit_branch = 'origin/master' AND\n\t\twal_device = '$wal_device' AND\n\t\tmax_connection_threads = 32\n\t\tORDER BY benchmark_type, time DESC\n) AS one_terminal_benchmarks\nLEFT JOIN (\n\tSELECT DISTINCT ON (terminals, benchmark_type)\n\t\ttime,\n\t\tbenchmark_type,\n\t\tterminals,\n\t\t(metrics->>'throughput')::float AS throughput\n\tFROM oltpbench_results\n\tWHERE\n\t  $__timeFilter(\"time\") AND\n\t\tclient_time = 60 AND\n\t\tgit_branch = 'origin/master' AND\n\t\twal_device = '$wal_device' AND\n\t\tmax_connection_threads = 32\n\t\tORDER BY terminals, benchmark_type, time DESC\n) AS all_terminal_benchmarks ON one_terminal_benchmarks.benchmark_type = all_terminal_benchmarks.benchmark_type) AS scaleability\nGROUP BY terminals\n\n"
    }
   ]
  },
  { "title": "Stability Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "tatp Throughput Stability",
   "type": "graph",
   "description": "The throughput over the course of the TATP benchmark. Throughput is sampled every 5 seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  NOW()+ CONCAT(incremental.time::text,' second')::interval - '10 minute'::interval as \"time\",\n\tTRIM('\"' FROM incremental.throughput::text)::numeric as \"throughput (tps)\"\nFROM \n  oltpbench_results oltp, LATERAL(\n  \tSELECT \n    \tvalue->'time' as \"time\",\n    \tvalue->'throughput' as \"throughput\"\n  \tFROM \n  \t  jsonb_array_elements(oltp.incremental_metrics)\n\t) incremental\nWHERE\n\toltp.time = (\n\t\tSELECT time\n\t\tFROM oltpbench_results\n\t\tWHERE\n\t\t  query_mode = 'extended' AND\n\t\t\tbenchmark_type = 'tatp' AND\n\t\t\tclient_time = 600 AND\n      git_branch = 'origin/master' AND\n      wal_device = '$wal_device' AND\n      max_connection_threads = 32\n\t\tORDER BY time DESC\n\t\tLIMIT 1\n\t);"
    }
   ]
  },
  {
   "title": "tatp Latency Stability",
   "type": "graph",
   "description": "The latency over the course of the TATP benchmark. Latency is sampled every 5 seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  NOW()+ CONCAT(incremental.time::text,' second')::interval - '10 minute'::interval as \"time\",\n\t(incremental.latency->>'avg')::numeric as \"avg (ms)\",\n\t(incremental.latency->>'l_90')::numeric as \"l_90 (ms)\",\n\t(incremental.latency->>'l_95')::numeric as \"l_95 (ms)\",\n\t(incremental.latency->>'l_99')::numeric as \"l_99 (ms)\"\nFROM \n  oltpbench_results oltp, LATERAL(\n  \tSELECT \n    \tvalue->'time' as \"time\",\n    \tvalue->'latency' as \"latency\"\n  \tFROM \n  \t  jsonb_array_elements(oltp.incremental_metrics)\n\t) incremental\nWHERE\n\toltp.time = (\n\t\tSELECT time\n\t\tFROM oltpbench_results\n\t\tWHERE\n\t\t  query_mode = 'extended' AND\n\t\t\tbenchmark_type = 'tatp' AND\n\t\t\tclient_time = 600 AND\n      git_branch = 'origin/master' AND\n      wal_device = '$wal_device' AND\n      max_connection_threads = 32\n\t\tORDER BY time DESC\n\t\tLIMIT 1\n\t);"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 64 },
   "content": "\n# NoisePage Performance\nBrought to you by the CMU-DB group.\n\n\n"
  }
 ]
}