{
 "title": "Throughput Trends",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "benchmark_type",
    "label": "Benchmark Type",
    "query": "SELECT benchmark_type FROM oltpbench_results"
   },
   {
    "name": "terminals",
    "label": "Terminals",
    "query": "SELECT terminals FROM oltpbench_results"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "\n# Throughput Trends\n\nThis dashboard display an overview of how throughput changes over time \nFor each benchmark you can compare throughput metrics for a specific\nnumber of terminals. You can also compare a throughput metric across \ndifferent terminal values. Feel free to mix and match, but be warned\nthe charts can get overwhelming pretty fast.\n\n\n\n"
  },
  { "title": "$benchmark_type", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }, "repeat": "benchmark_type" },
  {
   "title": "$benchmark_type Throughput Trend",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Throughput(req/s)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"terminals = 1\",\n  git_commit_id\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) AND\n  terminals = 1\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"terminals = 2\",\n  git_commit_id\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) AND\n  terminals = 2\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"terminals = 4\",\n  git_commit_id\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) AND\n  terminals = 4\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"terminals = 8\",\n  git_commit_id\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) AND\n  terminals = 8\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"terminals = 16\",\n  git_commit_id\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) AND\n  terminals = 16\nORDER BY time"
    }
   ]
  },
  {
   "title": "Max, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 0, "y": 18 },
   "repeat": "terminals",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) \nORDER BY \"Throughput\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Max, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 4.8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) \nORDER BY \"Throughput\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Max, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 9.6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) \nORDER BY \"Throughput\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Max, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 14.399999999999999, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) \nORDER BY \"Throughput\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Max, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 19.2, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) \nORDER BY \"Throughput\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Average, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 0, "y": 24 },
   "repeat": "terminals",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg((metrics->>'throughput')::jsonb::text::numeric) AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})"
    }
   ]
  },
  {
   "title": "Average, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 4.8, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg((metrics->>'throughput')::jsonb::text::numeric) AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})"
    }
   ]
  },
  {
   "title": "Average, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 9.6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg((metrics->>'throughput')::jsonb::text::numeric) AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})"
    }
   ]
  },
  {
   "title": "Average, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 14.399999999999999, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg((metrics->>'throughput')::jsonb::text::numeric) AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})"
    }
   ]
  },
  {
   "title": "Average, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 19.2, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg((metrics->>'throughput')::jsonb::text::numeric) AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})"
    }
   ]
  },
  {
   "title": "Min, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 0, "y": 30 },
   "repeat": "terminals",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Throughput\" ASC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Min, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 4.8, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Throughput\" ASC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Min, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 9.6, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Throughput\" ASC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Min, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 14.399999999999999, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Throughput\" ASC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Min, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 19.2, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Throughput\" ASC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Latest, terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4.8, "x": 0, "y": 36 },
   "repeat": "terminals",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') as \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\",\n  (FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) -\n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time asc)) / \n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) * 100 as \"Change\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Date\" DESC"
    }
   ]
  },
  {
   "title": "Latest, terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4.8, "x": 4.8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') as \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\",\n  (FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) -\n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time asc)) / \n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) * 100 as \"Change\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Date\" DESC"
    }
   ]
  },
  {
   "title": "Latest, terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4.8, "x": 9.6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') as \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\",\n  (FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) -\n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time asc)) / \n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) * 100 as \"Change\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Date\" DESC"
    }
   ]
  },
  {
   "title": "Latest, terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4.8, "x": 14.399999999999999, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') as \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\",\n  (FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) -\n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time asc)) / \n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) * 100 as \"Change\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Date\" DESC"
    }
   ]
  },
  {
   "title": "Latest, terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4.8, "x": 19.2, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') as \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\",\n  (FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) -\n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time asc)) / \n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) * 100 as \"Change\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Date\" DESC"
    }
   ]
  },
  { "title": "$benchmark_type", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "$benchmark_type Throughput Trend",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "Throughput(req/s)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"terminals = 1\",\n  git_commit_id\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) AND\n  terminals = 1\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"terminals = 2\",\n  git_commit_id\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) AND\n  terminals = 2\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"terminals = 4\",\n  git_commit_id\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) AND\n  terminals = 4\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"terminals = 8\",\n  git_commit_id\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) AND\n  terminals = 8\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"terminals = 16\",\n  git_commit_id\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) AND\n  terminals = 16\nORDER BY time"
    }
   ]
  },
  {
   "title": "Max, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 0, "y": 56 },
   "repeat": "terminals",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) \nORDER BY \"Throughput\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Max, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 4.8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) \nORDER BY \"Throughput\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Max, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 9.6, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) \nORDER BY \"Throughput\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Max, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 14.399999999999999, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) \nORDER BY \"Throughput\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Max, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 19.2, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) \nORDER BY \"Throughput\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Average, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 0, "y": 62 },
   "repeat": "terminals",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg((metrics->>'throughput')::jsonb::text::numeric) AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})"
    }
   ]
  },
  {
   "title": "Average, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 4.8, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg((metrics->>'throughput')::jsonb::text::numeric) AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})"
    }
   ]
  },
  {
   "title": "Average, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 9.6, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg((metrics->>'throughput')::jsonb::text::numeric) AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})"
    }
   ]
  },
  {
   "title": "Average, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 14.399999999999999, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg((metrics->>'throughput')::jsonb::text::numeric) AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})"
    }
   ]
  },
  {
   "title": "Average, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 19.2, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg((metrics->>'throughput')::jsonb::text::numeric) AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})"
    }
   ]
  },
  {
   "title": "Min, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 0, "y": 68 },
   "repeat": "terminals",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Throughput\" ASC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Min, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 4.8, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Throughput\" ASC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Min, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 9.6, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Throughput\" ASC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Min, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 14.399999999999999, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Throughput\" ASC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Min, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 19.2, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Throughput\" ASC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Latest, terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4.8, "x": 0, "y": 74 },
   "repeat": "terminals",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') as \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\",\n  (FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) -\n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time asc)) / \n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) * 100 as \"Change\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Date\" DESC"
    }
   ]
  },
  {
   "title": "Latest, terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4.8, "x": 4.8, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') as \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\",\n  (FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) -\n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time asc)) / \n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) * 100 as \"Change\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Date\" DESC"
    }
   ]
  },
  {
   "title": "Latest, terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4.8, "x": 9.6, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') as \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\",\n  (FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) -\n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time asc)) / \n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) * 100 as \"Change\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Date\" DESC"
    }
   ]
  },
  {
   "title": "Latest, terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4.8, "x": 14.399999999999999, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') as \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\",\n  (FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) -\n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time asc)) / \n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) * 100 as \"Change\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Date\" DESC"
    }
   ]
  },
  {
   "title": "Latest, terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4.8, "x": 19.2, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') as \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\",\n  (FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) -\n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time asc)) / \n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) * 100 as \"Change\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Date\" DESC"
    }
   ]
  },
  { "title": "$benchmark_type", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "$benchmark_type Throughput Trend",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short", "label": "Throughput(req/s)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"terminals = 1\",\n  git_commit_id\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) AND\n  terminals = 1\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"terminals = 2\",\n  git_commit_id\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) AND\n  terminals = 2\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"terminals = 4\",\n  git_commit_id\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) AND\n  terminals = 4\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"terminals = 8\",\n  git_commit_id\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) AND\n  terminals = 8\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"terminals = 16\",\n  git_commit_id\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) AND\n  terminals = 16\nORDER BY time"
    }
   ]
  },
  {
   "title": "Max, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 0, "y": 94 },
   "repeat": "terminals",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) \nORDER BY \"Throughput\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Max, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 4.8, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) \nORDER BY \"Throughput\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Max, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 9.6, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) \nORDER BY \"Throughput\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Max, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 14.399999999999999, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) \nORDER BY \"Throughput\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Max, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 19.2, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) \nORDER BY \"Throughput\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Average, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 0, "y": 100 },
   "repeat": "terminals",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg((metrics->>'throughput')::jsonb::text::numeric) AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})"
    }
   ]
  },
  {
   "title": "Average, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 4.8, "y": 100 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg((metrics->>'throughput')::jsonb::text::numeric) AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})"
    }
   ]
  },
  {
   "title": "Average, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 9.6, "y": 100 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg((metrics->>'throughput')::jsonb::text::numeric) AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})"
    }
   ]
  },
  {
   "title": "Average, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 14.399999999999999, "y": 100 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg((metrics->>'throughput')::jsonb::text::numeric) AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})"
    }
   ]
  },
  {
   "title": "Average, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 19.2, "y": 100 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg((metrics->>'throughput')::jsonb::text::numeric) AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})"
    }
   ]
  },
  {
   "title": "Min, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 0, "y": 106 },
   "repeat": "terminals",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Throughput\" ASC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Min, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 4.8, "y": 106 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Throughput\" ASC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Min, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 9.6, "y": 106 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Throughput\" ASC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Min, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 14.399999999999999, "y": 106 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Throughput\" ASC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Min, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 19.2, "y": 106 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Throughput\" ASC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Latest, terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4.8, "x": 0, "y": 112 },
   "repeat": "terminals",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') as \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\",\n  (FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) -\n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time asc)) / \n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) * 100 as \"Change\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Date\" DESC"
    }
   ]
  },
  {
   "title": "Latest, terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4.8, "x": 4.8, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') as \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\",\n  (FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) -\n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time asc)) / \n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) * 100 as \"Change\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Date\" DESC"
    }
   ]
  },
  {
   "title": "Latest, terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4.8, "x": 9.6, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') as \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\",\n  (FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) -\n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time asc)) / \n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) * 100 as \"Change\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Date\" DESC"
    }
   ]
  },
  {
   "title": "Latest, terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4.8, "x": 14.399999999999999, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') as \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\",\n  (FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) -\n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time asc)) / \n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) * 100 as \"Change\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Date\" DESC"
    }
   ]
  },
  {
   "title": "Latest, terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4.8, "x": 19.2, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') as \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\",\n  (FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) -\n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time asc)) / \n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) * 100 as \"Change\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Date\" DESC"
    }
   ]
  },
  { "title": "$benchmark_type", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 } },
  {
   "title": "$benchmark_type Throughput Trend",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "short", "label": "Throughput(req/s)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"terminals = 1\",\n  git_commit_id\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) AND\n  terminals = 1\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"terminals = 2\",\n  git_commit_id\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) AND\n  terminals = 2\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"terminals = 4\",\n  git_commit_id\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) AND\n  terminals = 4\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"terminals = 8\",\n  git_commit_id\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) AND\n  terminals = 8\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"terminals = 16\",\n  git_commit_id\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) AND\n  terminals = 16\nORDER BY time"
    }
   ]
  },
  {
   "title": "Max, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 0, "y": 132 },
   "repeat": "terminals",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) \nORDER BY \"Throughput\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Max, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 4.8, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) \nORDER BY \"Throughput\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Max, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 9.6, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) \nORDER BY \"Throughput\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Max, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 14.399999999999999, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) \nORDER BY \"Throughput\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Max, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 19.2, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) \nORDER BY \"Throughput\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Average, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 0, "y": 138 },
   "repeat": "terminals",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg((metrics->>'throughput')::jsonb::text::numeric) AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})"
    }
   ]
  },
  {
   "title": "Average, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 4.8, "y": 138 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg((metrics->>'throughput')::jsonb::text::numeric) AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})"
    }
   ]
  },
  {
   "title": "Average, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 9.6, "y": 138 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg((metrics->>'throughput')::jsonb::text::numeric) AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})"
    }
   ]
  },
  {
   "title": "Average, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 14.399999999999999, "y": 138 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg((metrics->>'throughput')::jsonb::text::numeric) AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})"
    }
   ]
  },
  {
   "title": "Average, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 19.2, "y": 138 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg((metrics->>'throughput')::jsonb::text::numeric) AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})"
    }
   ]
  },
  {
   "title": "Min, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 0, "y": 144 },
   "repeat": "terminals",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Throughput\" ASC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Min, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 4.8, "y": 144 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Throughput\" ASC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Min, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 9.6, "y": 144 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Throughput\" ASC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Min, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 14.399999999999999, "y": 144 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Throughput\" ASC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Min, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 19.2, "y": 144 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Throughput\" ASC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Latest, terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4.8, "x": 0, "y": 150 },
   "repeat": "terminals",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') as \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\",\n  (FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) -\n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time asc)) / \n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) * 100 as \"Change\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Date\" DESC"
    }
   ]
  },
  {
   "title": "Latest, terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4.8, "x": 4.8, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') as \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\",\n  (FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) -\n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time asc)) / \n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) * 100 as \"Change\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Date\" DESC"
    }
   ]
  },
  {
   "title": "Latest, terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4.8, "x": 9.6, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') as \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\",\n  (FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) -\n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time asc)) / \n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) * 100 as \"Change\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Date\" DESC"
    }
   ]
  },
  {
   "title": "Latest, terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4.8, "x": 14.399999999999999, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') as \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\",\n  (FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) -\n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time asc)) / \n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) * 100 as \"Change\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Date\" DESC"
    }
   ]
  },
  {
   "title": "Latest, terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4.8, "x": 19.2, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') as \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\",\n  (FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) -\n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time asc)) / \n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) * 100 as \"Change\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Date\" DESC"
    }
   ]
  },
  { "title": "$benchmark_type", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 155 } },
  {
   "title": "$benchmark_type Throughput Trend",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 156 },
   "yaxes": [
    { "format": "short", "label": "Throughput(req/s)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"terminals = 1\",\n  git_commit_id\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) AND\n  terminals = 1\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"terminals = 2\",\n  git_commit_id\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) AND\n  terminals = 2\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"terminals = 4\",\n  git_commit_id\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) AND\n  terminals = 4\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"terminals = 8\",\n  git_commit_id\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) AND\n  terminals = 8\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"terminals = 16\",\n  git_commit_id\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) AND\n  terminals = 16\nORDER BY time"
    }
   ]
  },
  {
   "title": "Max, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 0, "y": 170 },
   "repeat": "terminals",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) \nORDER BY \"Throughput\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Max, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 4.8, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) \nORDER BY \"Throughput\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Max, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 9.6, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) \nORDER BY \"Throughput\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Max, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 14.399999999999999, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) \nORDER BY \"Throughput\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Max, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 19.2, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals}) \nORDER BY \"Throughput\" DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Average, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 0, "y": 176 },
   "repeat": "terminals",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg((metrics->>'throughput')::jsonb::text::numeric) AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})"
    }
   ]
  },
  {
   "title": "Average, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 4.8, "y": 176 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg((metrics->>'throughput')::jsonb::text::numeric) AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})"
    }
   ]
  },
  {
   "title": "Average, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 9.6, "y": 176 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg((metrics->>'throughput')::jsonb::text::numeric) AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})"
    }
   ]
  },
  {
   "title": "Average, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 14.399999999999999, "y": 176 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg((metrics->>'throughput')::jsonb::text::numeric) AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})"
    }
   ]
  },
  {
   "title": "Average, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 19.2, "y": 176 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg((metrics->>'throughput')::jsonb::text::numeric) AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})"
    }
   ]
  },
  {
   "title": "Min, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 0, "y": 182 },
   "repeat": "terminals",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Throughput\" ASC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Min, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 4.8, "y": 182 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Throughput\" ASC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Min, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 9.6, "y": 182 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Throughput\" ASC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Min, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 14.399999999999999, "y": 182 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Throughput\" ASC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Min, Terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 19.2, "y": 182 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') AS \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Throughput\" ASC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Latest, terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4.8, "x": 0, "y": 188 },
   "repeat": "terminals",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') as \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\",\n  (FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) -\n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time asc)) / \n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) * 100 as \"Change\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Date\" DESC"
    }
   ]
  },
  {
   "title": "Latest, terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4.8, "x": 4.8, "y": 188 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') as \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\",\n  (FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) -\n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time asc)) / \n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) * 100 as \"Change\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Date\" DESC"
    }
   ]
  },
  {
   "title": "Latest, terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4.8, "x": 9.6, "y": 188 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') as \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\",\n  (FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) -\n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time asc)) / \n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) * 100 as \"Change\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Date\" DESC"
    }
   ]
  },
  {
   "title": "Latest, terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4.8, "x": 14.399999999999999, "y": 188 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') as \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\",\n  (FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) -\n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time asc)) / \n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) * 100 as \"Change\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Date\" DESC"
    }
   ]
  },
  {
   "title": "Latest, terminals = $terminals",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4.8, "x": 19.2, "y": 188 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(time, 'Mon DD') as \"Date\",\n  (metrics->>'throughput')::jsonb::text::numeric AS \"Throughput\",\n  (FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) -\n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time asc)) / \n  FIRST_VALUE((metrics->>'throughput')::jsonb::text::numeric) OVER(PARTITION BY terminals order by time desc) * 100 as \"Change\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  terminals IN (${terminals})\nORDER BY \"Date\" DESC"
    }
   ]
  }
 ]
}