{
 "title": "Throughput-terminal Trends",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "benchmark_type",
    "label": "Benchmark Type",
    "query": "SELECT benchmark_type FROM oltpbench_results"
   },
   {
    "name": "terminals",
    "query": "SELECT terminals FROM oltpbench_results"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 20, "x": 0, "y": 0 },
   "content": "\n# Throughput-terminal Trends\n\nThis dashboard display an overview of how throughput changes over terminal numbers. Feel free to mix and match, but be warned the charts can get overwhelming pretty fast.\n"
  },
  {
   "title": "Commit ID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  git_commit_id\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n   benchmark_type = 'tatp'\nORDER BY time ASC"
    }
   ]
  },
  { "title": "$benchmark_type", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }, "repeat": "benchmark_type" },
  {
   "title": "$benchmark_type throughput-terminal trend",
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (terminals)\n\ttime, \n\tCAST(terminals AS TEXT) as metric,\n  CAST(metrics->>'throughput' AS DOUBLE PRECISION) as value\nFROM oltpbench_results\nWHERE \n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  client_time = 60 AND\n  git_branch = 'master'\nORDER BY terminals, time desc;"
    }
   ]
  },
  {
   "title": "$benchmark_type terminal=$terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 0, "y": 13 },
   "repeat": "terminals",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (terminals)\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION) as throughput,\r\n   expect_throughput,\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION)-expect_throughput as diff_throughput\r\nFROM oltpbench_results\r\nCROSS JOIN (\r\n\tSELECT (${terminals})*CAST(metrics->>'throughput' AS DOUBLE PRECISION) as expect_throughput\r\n\t\tFROM oltpbench_results\r\n\tWHERE\r\n\t   benchmark_type = ${benchmark_type}\r\n\t   AND terminals = 1 AND\r\n\t   client_time = 60 AND\r\n\t   git_branch = 'master'\r\n\t GROUP BY time, benchmark_type, terminals, metrics->>'throughput'\r\n\t ORDER BY time desc\r\n\t LIMIT 1\r\n) AS base\r\nWHERE\r\n   benchmark_type = ${benchmark_type} AND\r\n   terminals = (${terminals}) AND\r\n   client_time = 60 AND\r\n   git_branch = 'master'\r\nORDER BY terminals, time desc;"
    }
   ]
  },
  {
   "title": "$benchmark_type terminal=$terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 4.8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (terminals)\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION) as throughput,\r\n   expect_throughput,\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION)-expect_throughput as diff_throughput\r\nFROM oltpbench_results\r\nCROSS JOIN (\r\n\tSELECT (${terminals})*CAST(metrics->>'throughput' AS DOUBLE PRECISION) as expect_throughput\r\n\t\tFROM oltpbench_results\r\n\tWHERE\r\n\t   benchmark_type = ${benchmark_type}\r\n\t   AND terminals = 1 AND\r\n\t   client_time = 60 AND\r\n\t   git_branch = 'master'\r\n\t GROUP BY time, benchmark_type, terminals, metrics->>'throughput'\r\n\t ORDER BY time desc\r\n\t LIMIT 1\r\n) AS base\r\nWHERE\r\n   benchmark_type = ${benchmark_type} AND\r\n   terminals = (${terminals}) AND\r\n   client_time = 60 AND\r\n   git_branch = 'master'\r\nORDER BY terminals, time desc;"
    }
   ]
  },
  {
   "title": "$benchmark_type terminal=$terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 9.6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (terminals)\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION) as throughput,\r\n   expect_throughput,\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION)-expect_throughput as diff_throughput\r\nFROM oltpbench_results\r\nCROSS JOIN (\r\n\tSELECT (${terminals})*CAST(metrics->>'throughput' AS DOUBLE PRECISION) as expect_throughput\r\n\t\tFROM oltpbench_results\r\n\tWHERE\r\n\t   benchmark_type = ${benchmark_type}\r\n\t   AND terminals = 1 AND\r\n\t   client_time = 60 AND\r\n\t   git_branch = 'master'\r\n\t GROUP BY time, benchmark_type, terminals, metrics->>'throughput'\r\n\t ORDER BY time desc\r\n\t LIMIT 1\r\n) AS base\r\nWHERE\r\n   benchmark_type = ${benchmark_type} AND\r\n   terminals = (${terminals}) AND\r\n   client_time = 60 AND\r\n   git_branch = 'master'\r\nORDER BY terminals, time desc;"
    }
   ]
  },
  {
   "title": "$benchmark_type terminal=$terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 14.399999999999999, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (terminals)\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION) as throughput,\r\n   expect_throughput,\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION)-expect_throughput as diff_throughput\r\nFROM oltpbench_results\r\nCROSS JOIN (\r\n\tSELECT (${terminals})*CAST(metrics->>'throughput' AS DOUBLE PRECISION) as expect_throughput\r\n\t\tFROM oltpbench_results\r\n\tWHERE\r\n\t   benchmark_type = ${benchmark_type}\r\n\t   AND terminals = 1 AND\r\n\t   client_time = 60 AND\r\n\t   git_branch = 'master'\r\n\t GROUP BY time, benchmark_type, terminals, metrics->>'throughput'\r\n\t ORDER BY time desc\r\n\t LIMIT 1\r\n) AS base\r\nWHERE\r\n   benchmark_type = ${benchmark_type} AND\r\n   terminals = (${terminals}) AND\r\n   client_time = 60 AND\r\n   git_branch = 'master'\r\nORDER BY terminals, time desc;"
    }
   ]
  },
  {
   "title": "$benchmark_type terminal=$terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 19.2, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (terminals)\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION) as throughput,\r\n   expect_throughput,\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION)-expect_throughput as diff_throughput\r\nFROM oltpbench_results\r\nCROSS JOIN (\r\n\tSELECT (${terminals})*CAST(metrics->>'throughput' AS DOUBLE PRECISION) as expect_throughput\r\n\t\tFROM oltpbench_results\r\n\tWHERE\r\n\t   benchmark_type = ${benchmark_type}\r\n\t   AND terminals = 1 AND\r\n\t   client_time = 60 AND\r\n\t   git_branch = 'master'\r\n\t GROUP BY time, benchmark_type, terminals, metrics->>'throughput'\r\n\t ORDER BY time desc\r\n\t LIMIT 1\r\n) AS base\r\nWHERE\r\n   benchmark_type = ${benchmark_type} AND\r\n   terminals = (${terminals}) AND\r\n   client_time = 60 AND\r\n   git_branch = 'master'\r\nORDER BY terminals, time desc;"
    }
   ]
  },
  { "title": "$benchmark_type", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "$benchmark_type throughput-terminal trend",
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (terminals)\n\ttime, \n\tCAST(terminals AS TEXT) as metric,\n  CAST(metrics->>'throughput' AS DOUBLE PRECISION) as value\nFROM oltpbench_results\nWHERE \n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  client_time = 60 AND\n  git_branch = 'master'\nORDER BY terminals, time desc;"
    }
   ]
  },
  {
   "title": "$benchmark_type terminal=$terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 0, "y": 29 },
   "repeat": "terminals",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (terminals)\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION) as throughput,\r\n   expect_throughput,\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION)-expect_throughput as diff_throughput\r\nFROM oltpbench_results\r\nCROSS JOIN (\r\n\tSELECT (${terminals})*CAST(metrics->>'throughput' AS DOUBLE PRECISION) as expect_throughput\r\n\t\tFROM oltpbench_results\r\n\tWHERE\r\n\t   benchmark_type = ${benchmark_type}\r\n\t   AND terminals = 1 AND\r\n\t   client_time = 60 AND\r\n\t   git_branch = 'master'\r\n\t GROUP BY time, benchmark_type, terminals, metrics->>'throughput'\r\n\t ORDER BY time desc\r\n\t LIMIT 1\r\n) AS base\r\nWHERE\r\n   benchmark_type = ${benchmark_type} AND\r\n   terminals = (${terminals}) AND\r\n   client_time = 60 AND\r\n   git_branch = 'master'\r\nORDER BY terminals, time desc;"
    }
   ]
  },
  {
   "title": "$benchmark_type terminal=$terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 4.8, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (terminals)\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION) as throughput,\r\n   expect_throughput,\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION)-expect_throughput as diff_throughput\r\nFROM oltpbench_results\r\nCROSS JOIN (\r\n\tSELECT (${terminals})*CAST(metrics->>'throughput' AS DOUBLE PRECISION) as expect_throughput\r\n\t\tFROM oltpbench_results\r\n\tWHERE\r\n\t   benchmark_type = ${benchmark_type}\r\n\t   AND terminals = 1 AND\r\n\t   client_time = 60 AND\r\n\t   git_branch = 'master'\r\n\t GROUP BY time, benchmark_type, terminals, metrics->>'throughput'\r\n\t ORDER BY time desc\r\n\t LIMIT 1\r\n) AS base\r\nWHERE\r\n   benchmark_type = ${benchmark_type} AND\r\n   terminals = (${terminals}) AND\r\n   client_time = 60 AND\r\n   git_branch = 'master'\r\nORDER BY terminals, time desc;"
    }
   ]
  },
  {
   "title": "$benchmark_type terminal=$terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 9.6, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (terminals)\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION) as throughput,\r\n   expect_throughput,\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION)-expect_throughput as diff_throughput\r\nFROM oltpbench_results\r\nCROSS JOIN (\r\n\tSELECT (${terminals})*CAST(metrics->>'throughput' AS DOUBLE PRECISION) as expect_throughput\r\n\t\tFROM oltpbench_results\r\n\tWHERE\r\n\t   benchmark_type = ${benchmark_type}\r\n\t   AND terminals = 1 AND\r\n\t   client_time = 60 AND\r\n\t   git_branch = 'master'\r\n\t GROUP BY time, benchmark_type, terminals, metrics->>'throughput'\r\n\t ORDER BY time desc\r\n\t LIMIT 1\r\n) AS base\r\nWHERE\r\n   benchmark_type = ${benchmark_type} AND\r\n   terminals = (${terminals}) AND\r\n   client_time = 60 AND\r\n   git_branch = 'master'\r\nORDER BY terminals, time desc;"
    }
   ]
  },
  {
   "title": "$benchmark_type terminal=$terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 14.399999999999999, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (terminals)\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION) as throughput,\r\n   expect_throughput,\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION)-expect_throughput as diff_throughput\r\nFROM oltpbench_results\r\nCROSS JOIN (\r\n\tSELECT (${terminals})*CAST(metrics->>'throughput' AS DOUBLE PRECISION) as expect_throughput\r\n\t\tFROM oltpbench_results\r\n\tWHERE\r\n\t   benchmark_type = ${benchmark_type}\r\n\t   AND terminals = 1 AND\r\n\t   client_time = 60 AND\r\n\t   git_branch = 'master'\r\n\t GROUP BY time, benchmark_type, terminals, metrics->>'throughput'\r\n\t ORDER BY time desc\r\n\t LIMIT 1\r\n) AS base\r\nWHERE\r\n   benchmark_type = ${benchmark_type} AND\r\n   terminals = (${terminals}) AND\r\n   client_time = 60 AND\r\n   git_branch = 'master'\r\nORDER BY terminals, time desc;"
    }
   ]
  },
  {
   "title": "$benchmark_type terminal=$terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 19.2, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (terminals)\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION) as throughput,\r\n   expect_throughput,\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION)-expect_throughput as diff_throughput\r\nFROM oltpbench_results\r\nCROSS JOIN (\r\n\tSELECT (${terminals})*CAST(metrics->>'throughput' AS DOUBLE PRECISION) as expect_throughput\r\n\t\tFROM oltpbench_results\r\n\tWHERE\r\n\t   benchmark_type = ${benchmark_type}\r\n\t   AND terminals = 1 AND\r\n\t   client_time = 60 AND\r\n\t   git_branch = 'master'\r\n\t GROUP BY time, benchmark_type, terminals, metrics->>'throughput'\r\n\t ORDER BY time desc\r\n\t LIMIT 1\r\n) AS base\r\nWHERE\r\n   benchmark_type = ${benchmark_type} AND\r\n   terminals = (${terminals}) AND\r\n   client_time = 60 AND\r\n   git_branch = 'master'\r\nORDER BY terminals, time desc;"
    }
   ]
  },
  { "title": "$benchmark_type", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "$benchmark_type throughput-terminal trend",
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (terminals)\n\ttime, \n\tCAST(terminals AS TEXT) as metric,\n  CAST(metrics->>'throughput' AS DOUBLE PRECISION) as value\nFROM oltpbench_results\nWHERE \n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  client_time = 60 AND\n  git_branch = 'master'\nORDER BY terminals, time desc;"
    }
   ]
  },
  {
   "title": "$benchmark_type terminal=$terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 0, "y": 45 },
   "repeat": "terminals",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (terminals)\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION) as throughput,\r\n   expect_throughput,\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION)-expect_throughput as diff_throughput\r\nFROM oltpbench_results\r\nCROSS JOIN (\r\n\tSELECT (${terminals})*CAST(metrics->>'throughput' AS DOUBLE PRECISION) as expect_throughput\r\n\t\tFROM oltpbench_results\r\n\tWHERE\r\n\t   benchmark_type = ${benchmark_type}\r\n\t   AND terminals = 1 AND\r\n\t   client_time = 60 AND\r\n\t   git_branch = 'master'\r\n\t GROUP BY time, benchmark_type, terminals, metrics->>'throughput'\r\n\t ORDER BY time desc\r\n\t LIMIT 1\r\n) AS base\r\nWHERE\r\n   benchmark_type = ${benchmark_type} AND\r\n   terminals = (${terminals}) AND\r\n   client_time = 60 AND\r\n   git_branch = 'master'\r\nORDER BY terminals, time desc;"
    }
   ]
  },
  {
   "title": "$benchmark_type terminal=$terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 4.8, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (terminals)\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION) as throughput,\r\n   expect_throughput,\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION)-expect_throughput as diff_throughput\r\nFROM oltpbench_results\r\nCROSS JOIN (\r\n\tSELECT (${terminals})*CAST(metrics->>'throughput' AS DOUBLE PRECISION) as expect_throughput\r\n\t\tFROM oltpbench_results\r\n\tWHERE\r\n\t   benchmark_type = ${benchmark_type}\r\n\t   AND terminals = 1 AND\r\n\t   client_time = 60 AND\r\n\t   git_branch = 'master'\r\n\t GROUP BY time, benchmark_type, terminals, metrics->>'throughput'\r\n\t ORDER BY time desc\r\n\t LIMIT 1\r\n) AS base\r\nWHERE\r\n   benchmark_type = ${benchmark_type} AND\r\n   terminals = (${terminals}) AND\r\n   client_time = 60 AND\r\n   git_branch = 'master'\r\nORDER BY terminals, time desc;"
    }
   ]
  },
  {
   "title": "$benchmark_type terminal=$terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 9.6, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (terminals)\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION) as throughput,\r\n   expect_throughput,\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION)-expect_throughput as diff_throughput\r\nFROM oltpbench_results\r\nCROSS JOIN (\r\n\tSELECT (${terminals})*CAST(metrics->>'throughput' AS DOUBLE PRECISION) as expect_throughput\r\n\t\tFROM oltpbench_results\r\n\tWHERE\r\n\t   benchmark_type = ${benchmark_type}\r\n\t   AND terminals = 1 AND\r\n\t   client_time = 60 AND\r\n\t   git_branch = 'master'\r\n\t GROUP BY time, benchmark_type, terminals, metrics->>'throughput'\r\n\t ORDER BY time desc\r\n\t LIMIT 1\r\n) AS base\r\nWHERE\r\n   benchmark_type = ${benchmark_type} AND\r\n   terminals = (${terminals}) AND\r\n   client_time = 60 AND\r\n   git_branch = 'master'\r\nORDER BY terminals, time desc;"
    }
   ]
  },
  {
   "title": "$benchmark_type terminal=$terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 14.399999999999999, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (terminals)\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION) as throughput,\r\n   expect_throughput,\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION)-expect_throughput as diff_throughput\r\nFROM oltpbench_results\r\nCROSS JOIN (\r\n\tSELECT (${terminals})*CAST(metrics->>'throughput' AS DOUBLE PRECISION) as expect_throughput\r\n\t\tFROM oltpbench_results\r\n\tWHERE\r\n\t   benchmark_type = ${benchmark_type}\r\n\t   AND terminals = 1 AND\r\n\t   client_time = 60 AND\r\n\t   git_branch = 'master'\r\n\t GROUP BY time, benchmark_type, terminals, metrics->>'throughput'\r\n\t ORDER BY time desc\r\n\t LIMIT 1\r\n) AS base\r\nWHERE\r\n   benchmark_type = ${benchmark_type} AND\r\n   terminals = (${terminals}) AND\r\n   client_time = 60 AND\r\n   git_branch = 'master'\r\nORDER BY terminals, time desc;"
    }
   ]
  },
  {
   "title": "$benchmark_type terminal=$terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 19.2, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (terminals)\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION) as throughput,\r\n   expect_throughput,\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION)-expect_throughput as diff_throughput\r\nFROM oltpbench_results\r\nCROSS JOIN (\r\n\tSELECT (${terminals})*CAST(metrics->>'throughput' AS DOUBLE PRECISION) as expect_throughput\r\n\t\tFROM oltpbench_results\r\n\tWHERE\r\n\t   benchmark_type = ${benchmark_type}\r\n\t   AND terminals = 1 AND\r\n\t   client_time = 60 AND\r\n\t   git_branch = 'master'\r\n\t GROUP BY time, benchmark_type, terminals, metrics->>'throughput'\r\n\t ORDER BY time desc\r\n\t LIMIT 1\r\n) AS base\r\nWHERE\r\n   benchmark_type = ${benchmark_type} AND\r\n   terminals = (${terminals}) AND\r\n   client_time = 60 AND\r\n   git_branch = 'master'\r\nORDER BY terminals, time desc;"
    }
   ]
  },
  { "title": "$benchmark_type", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "$benchmark_type throughput-terminal trend",
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (terminals)\n\ttime, \n\tCAST(terminals AS TEXT) as metric,\n  CAST(metrics->>'throughput' AS DOUBLE PRECISION) as value\nFROM oltpbench_results\nWHERE \n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  client_time = 60 AND\n  git_branch = 'master'\nORDER BY terminals, time desc;"
    }
   ]
  },
  {
   "title": "$benchmark_type terminal=$terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 0, "y": 61 },
   "repeat": "terminals",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (terminals)\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION) as throughput,\r\n   expect_throughput,\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION)-expect_throughput as diff_throughput\r\nFROM oltpbench_results\r\nCROSS JOIN (\r\n\tSELECT (${terminals})*CAST(metrics->>'throughput' AS DOUBLE PRECISION) as expect_throughput\r\n\t\tFROM oltpbench_results\r\n\tWHERE\r\n\t   benchmark_type = ${benchmark_type}\r\n\t   AND terminals = 1 AND\r\n\t   client_time = 60 AND\r\n\t   git_branch = 'master'\r\n\t GROUP BY time, benchmark_type, terminals, metrics->>'throughput'\r\n\t ORDER BY time desc\r\n\t LIMIT 1\r\n) AS base\r\nWHERE\r\n   benchmark_type = ${benchmark_type} AND\r\n   terminals = (${terminals}) AND\r\n   client_time = 60 AND\r\n   git_branch = 'master'\r\nORDER BY terminals, time desc;"
    }
   ]
  },
  {
   "title": "$benchmark_type terminal=$terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 4.8, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (terminals)\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION) as throughput,\r\n   expect_throughput,\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION)-expect_throughput as diff_throughput\r\nFROM oltpbench_results\r\nCROSS JOIN (\r\n\tSELECT (${terminals})*CAST(metrics->>'throughput' AS DOUBLE PRECISION) as expect_throughput\r\n\t\tFROM oltpbench_results\r\n\tWHERE\r\n\t   benchmark_type = ${benchmark_type}\r\n\t   AND terminals = 1 AND\r\n\t   client_time = 60 AND\r\n\t   git_branch = 'master'\r\n\t GROUP BY time, benchmark_type, terminals, metrics->>'throughput'\r\n\t ORDER BY time desc\r\n\t LIMIT 1\r\n) AS base\r\nWHERE\r\n   benchmark_type = ${benchmark_type} AND\r\n   terminals = (${terminals}) AND\r\n   client_time = 60 AND\r\n   git_branch = 'master'\r\nORDER BY terminals, time desc;"
    }
   ]
  },
  {
   "title": "$benchmark_type terminal=$terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 9.6, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (terminals)\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION) as throughput,\r\n   expect_throughput,\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION)-expect_throughput as diff_throughput\r\nFROM oltpbench_results\r\nCROSS JOIN (\r\n\tSELECT (${terminals})*CAST(metrics->>'throughput' AS DOUBLE PRECISION) as expect_throughput\r\n\t\tFROM oltpbench_results\r\n\tWHERE\r\n\t   benchmark_type = ${benchmark_type}\r\n\t   AND terminals = 1 AND\r\n\t   client_time = 60 AND\r\n\t   git_branch = 'master'\r\n\t GROUP BY time, benchmark_type, terminals, metrics->>'throughput'\r\n\t ORDER BY time desc\r\n\t LIMIT 1\r\n) AS base\r\nWHERE\r\n   benchmark_type = ${benchmark_type} AND\r\n   terminals = (${terminals}) AND\r\n   client_time = 60 AND\r\n   git_branch = 'master'\r\nORDER BY terminals, time desc;"
    }
   ]
  },
  {
   "title": "$benchmark_type terminal=$terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 14.399999999999999, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (terminals)\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION) as throughput,\r\n   expect_throughput,\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION)-expect_throughput as diff_throughput\r\nFROM oltpbench_results\r\nCROSS JOIN (\r\n\tSELECT (${terminals})*CAST(metrics->>'throughput' AS DOUBLE PRECISION) as expect_throughput\r\n\t\tFROM oltpbench_results\r\n\tWHERE\r\n\t   benchmark_type = ${benchmark_type}\r\n\t   AND terminals = 1 AND\r\n\t   client_time = 60 AND\r\n\t   git_branch = 'master'\r\n\t GROUP BY time, benchmark_type, terminals, metrics->>'throughput'\r\n\t ORDER BY time desc\r\n\t LIMIT 1\r\n) AS base\r\nWHERE\r\n   benchmark_type = ${benchmark_type} AND\r\n   terminals = (${terminals}) AND\r\n   client_time = 60 AND\r\n   git_branch = 'master'\r\nORDER BY terminals, time desc;"
    }
   ]
  },
  {
   "title": "$benchmark_type terminal=$terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 19.2, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (terminals)\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION) as throughput,\r\n   expect_throughput,\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION)-expect_throughput as diff_throughput\r\nFROM oltpbench_results\r\nCROSS JOIN (\r\n\tSELECT (${terminals})*CAST(metrics->>'throughput' AS DOUBLE PRECISION) as expect_throughput\r\n\t\tFROM oltpbench_results\r\n\tWHERE\r\n\t   benchmark_type = ${benchmark_type}\r\n\t   AND terminals = 1 AND\r\n\t   client_time = 60 AND\r\n\t   git_branch = 'master'\r\n\t GROUP BY time, benchmark_type, terminals, metrics->>'throughput'\r\n\t ORDER BY time desc\r\n\t LIMIT 1\r\n) AS base\r\nWHERE\r\n   benchmark_type = ${benchmark_type} AND\r\n   terminals = (${terminals}) AND\r\n   client_time = 60 AND\r\n   git_branch = 'master'\r\nORDER BY terminals, time desc;"
    }
   ]
  },
  { "title": "$benchmark_type", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "$benchmark_type throughput-terminal trend",
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (terminals)\n\ttime, \n\tCAST(terminals AS TEXT) as metric,\n  CAST(metrics->>'throughput' AS DOUBLE PRECISION) as value\nFROM oltpbench_results\nWHERE \n  $__timeFilter(\"time\") AND\n  benchmark_type = ${benchmark_type} AND\n  client_time = 60 AND\n  git_branch = 'master'\nORDER BY terminals, time desc;"
    }
   ]
  },
  {
   "title": "$benchmark_type terminal=$terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 0, "y": 77 },
   "repeat": "terminals",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (terminals)\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION) as throughput,\r\n   expect_throughput,\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION)-expect_throughput as diff_throughput\r\nFROM oltpbench_results\r\nCROSS JOIN (\r\n\tSELECT (${terminals})*CAST(metrics->>'throughput' AS DOUBLE PRECISION) as expect_throughput\r\n\t\tFROM oltpbench_results\r\n\tWHERE\r\n\t   benchmark_type = ${benchmark_type}\r\n\t   AND terminals = 1 AND\r\n\t   client_time = 60 AND\r\n\t   git_branch = 'master'\r\n\t GROUP BY time, benchmark_type, terminals, metrics->>'throughput'\r\n\t ORDER BY time desc\r\n\t LIMIT 1\r\n) AS base\r\nWHERE\r\n   benchmark_type = ${benchmark_type} AND\r\n   terminals = (${terminals}) AND\r\n   client_time = 60 AND\r\n   git_branch = 'master'\r\nORDER BY terminals, time desc;"
    }
   ]
  },
  {
   "title": "$benchmark_type terminal=$terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 4.8, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (terminals)\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION) as throughput,\r\n   expect_throughput,\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION)-expect_throughput as diff_throughput\r\nFROM oltpbench_results\r\nCROSS JOIN (\r\n\tSELECT (${terminals})*CAST(metrics->>'throughput' AS DOUBLE PRECISION) as expect_throughput\r\n\t\tFROM oltpbench_results\r\n\tWHERE\r\n\t   benchmark_type = ${benchmark_type}\r\n\t   AND terminals = 1 AND\r\n\t   client_time = 60 AND\r\n\t   git_branch = 'master'\r\n\t GROUP BY time, benchmark_type, terminals, metrics->>'throughput'\r\n\t ORDER BY time desc\r\n\t LIMIT 1\r\n) AS base\r\nWHERE\r\n   benchmark_type = ${benchmark_type} AND\r\n   terminals = (${terminals}) AND\r\n   client_time = 60 AND\r\n   git_branch = 'master'\r\nORDER BY terminals, time desc;"
    }
   ]
  },
  {
   "title": "$benchmark_type terminal=$terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 9.6, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (terminals)\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION) as throughput,\r\n   expect_throughput,\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION)-expect_throughput as diff_throughput\r\nFROM oltpbench_results\r\nCROSS JOIN (\r\n\tSELECT (${terminals})*CAST(metrics->>'throughput' AS DOUBLE PRECISION) as expect_throughput\r\n\t\tFROM oltpbench_results\r\n\tWHERE\r\n\t   benchmark_type = ${benchmark_type}\r\n\t   AND terminals = 1 AND\r\n\t   client_time = 60 AND\r\n\t   git_branch = 'master'\r\n\t GROUP BY time, benchmark_type, terminals, metrics->>'throughput'\r\n\t ORDER BY time desc\r\n\t LIMIT 1\r\n) AS base\r\nWHERE\r\n   benchmark_type = ${benchmark_type} AND\r\n   terminals = (${terminals}) AND\r\n   client_time = 60 AND\r\n   git_branch = 'master'\r\nORDER BY terminals, time desc;"
    }
   ]
  },
  {
   "title": "$benchmark_type terminal=$terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 14.399999999999999, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (terminals)\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION) as throughput,\r\n   expect_throughput,\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION)-expect_throughput as diff_throughput\r\nFROM oltpbench_results\r\nCROSS JOIN (\r\n\tSELECT (${terminals})*CAST(metrics->>'throughput' AS DOUBLE PRECISION) as expect_throughput\r\n\t\tFROM oltpbench_results\r\n\tWHERE\r\n\t   benchmark_type = ${benchmark_type}\r\n\t   AND terminals = 1 AND\r\n\t   client_time = 60 AND\r\n\t   git_branch = 'master'\r\n\t GROUP BY time, benchmark_type, terminals, metrics->>'throughput'\r\n\t ORDER BY time desc\r\n\t LIMIT 1\r\n) AS base\r\nWHERE\r\n   benchmark_type = ${benchmark_type} AND\r\n   terminals = (${terminals}) AND\r\n   client_time = 60 AND\r\n   git_branch = 'master'\r\nORDER BY terminals, time desc;"
    }
   ]
  },
  {
   "title": "$benchmark_type terminal=$terminals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4.8, "x": 19.2, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (terminals)\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION) as throughput,\r\n   expect_throughput,\r\n   CAST(metrics->>'throughput' AS DOUBLE PRECISION)-expect_throughput as diff_throughput\r\nFROM oltpbench_results\r\nCROSS JOIN (\r\n\tSELECT (${terminals})*CAST(metrics->>'throughput' AS DOUBLE PRECISION) as expect_throughput\r\n\t\tFROM oltpbench_results\r\n\tWHERE\r\n\t   benchmark_type = ${benchmark_type}\r\n\t   AND terminals = 1 AND\r\n\t   client_time = 60 AND\r\n\t   git_branch = 'master'\r\n\t GROUP BY time, benchmark_type, terminals, metrics->>'throughput'\r\n\t ORDER BY time desc\r\n\t LIMIT 1\r\n) AS base\r\nWHERE\r\n   benchmark_type = ${benchmark_type} AND\r\n   terminals = (${terminals}) AND\r\n   client_time = 60 AND\r\n   git_branch = 'master'\r\nORDER BY terminals, time desc;"
    }
   ]
  }
 ]
}