---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: performance-storage-service
  namespace: performance
  labels:
    app: pss
    env: local
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: pss
      env: local
  template:
    metadata:
      labels:
        app: pss
        env: local
    spec:
      containers:
        - name: performance-storage-service
          image: "{{ container_image }}"
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: SECRET_KEY
              value: "super-secret"
