{
 "title": "Nightly",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Last TATP",
   "type": "stat",
   "description": "terminals = 16\n\nclient-time = 60",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n   CAST(result->>'throughput' AS DOUBLE PRECISION) AS \"throughput\"\nFROM test_table\nWHERE\n   $__timeFilter(\"time\") AND\n   benchmark_type = 'tatp' AND\n   terminals = '16'\n"
    }
   ]
  },
  {
   "title": "Best TATP",
   "type": "stat",
   "description": "terminals = 16\n\nclient-time = 60",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n   MAX(CAST(result->>'throughput' AS DOUBLE PRECISION)) AS \"throughput\"\nFROM test_table\nWHERE\n   $__timeFilter(\"time\") AND\n   benchmark_type = 'tatp' AND\n   terminals = '16'\nGROUP BY terminals\nORDER BY 1"
    }
   ]
  },
  {
   "title": "AVG TATP",
   "type": "stat",
   "description": "terminals = 16\n\nclient-time = 60",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n   AVG(CAST(result->>'throughput' AS DOUBLE PRECISION)) AS \"throughput\"\nFROM test_table\nWHERE\n   $__timeFilter(\"time\") AND\n   benchmark_type = 'tatp' AND\n   terminals = '16'\nGROUP BY terminals\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Worst TATP",
   "type": "stat",
   "description": "terminals = 16\n\nclient-time = 60",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n   min(CAST(result->>'throughput' AS DOUBLE PRECISION)) AS \"throughput\"\nFROM test_table\nWHERE\n   $__timeFilter(\"time\") AND\n   benchmark_type = 'tatp' AND\n   terminals = '16'\nGROUP BY terminals\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Last NOOP",
   "type": "stat",
   "description": "terminals = 16\n\nclient-time = 60",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n   CAST(result->>'throughput' AS DOUBLE PRECISION) AS \"throughput\"\nFROM test_table\nWHERE\n   $__timeFilter(\"time\") AND\n   benchmark_type = 'noop' AND\n   terminals = '16'\n"
    }
   ]
  },
  {
   "title": "Best NOOP",
   "type": "stat",
   "description": "terminals = 16\n\nclient-time = 60",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n   MAX(CAST(result->>'throughput' AS DOUBLE PRECISION)) AS \"throughput\"\nFROM test_table\nWHERE\n   $__timeFilter(\"time\") AND\n   benchmark_type = 'noop' AND\n   terminals = '16'\nGROUP BY terminals\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Worst NOOP",
   "type": "stat",
   "description": "terminals = 16\n\nclient-time = 60",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n   min(CAST(result->>'throughput' AS DOUBLE PRECISION)) AS \"throughput\"\nFROM test_table\nWHERE\n   $__timeFilter(\"time\") AND\n   benchmark_type = 'noop' AND\n   terminals = '16'\nGROUP BY terminals\nORDER BY 1"
    }
   ]
  },
  {
   "title": "AVG NOOP",
   "type": "stat",
   "description": "terminals = 16\n\nclient-time = 60",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n   AVG(CAST(result->>'throughput' AS DOUBLE PRECISION)) AS \"throughput\"\nFROM test_table\nWHERE\n   $__timeFilter(\"time\") AND\n   benchmark_type = 'noop' AND\n   terminals = '16'\nGROUP BY terminals\nORDER BY 1"
    }
   ]
  },
  {
   "title": "TATP",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "throughput" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 1\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_table\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'tatp' AND\n  terminals = '1'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 2\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_table\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'tatp' AND\n  terminals = '2'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 4\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_table\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'tatp' AND\n  terminals = '4'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 8\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_table\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'tatp' AND\n  terminals = '8'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 16\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_table\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'tatp' AND\n  terminals = '16'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "NOOP",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "throughput" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 1\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_table\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'noop' AND\n  terminals = '1'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 2\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_table\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'noop' AND\n  terminals = '2'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 4\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_table\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'noop' AND\n  terminals = '4'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 8\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_table\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'noop' AND\n  terminals = '8'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 16\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_table\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'noop' AND\n  terminals = '16'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Last TPCC",
   "type": "stat",
   "description": "terminals = 16\n\nclient-time = 60",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n   CAST(result->>'throughput' AS DOUBLE PRECISION) AS \"throughput\"\nFROM test_table\nWHERE\n   $__timeFilter(\"time\") AND\n   benchmark_type = 'tpcc' AND\n   terminals = '16'\n"
    }
   ]
  },
  {
   "title": "Best TPCC",
   "type": "stat",
   "description": "terminals = 16\n\nclient-time = 60",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n   MAX(CAST(result->>'throughput' AS DOUBLE PRECISION)) AS \"throughput\"\nFROM test_table\nWHERE\n   $__timeFilter(\"time\") AND\n   benchmark_type = 'tpcc' AND\n   terminals = '16'\nGROUP BY terminals\nORDER BY 1"
    }
   ]
  },
  {
   "title": "AVG TPCC",
   "type": "stat",
   "description": "terminals = 16\n\nclient-time = 60",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n   AVG(CAST(result->>'throughput' AS DOUBLE PRECISION)) AS \"throughput\"\nFROM test_table\nWHERE\n   $__timeFilter(\"time\") AND\n   benchmark_type = 'tpcc' AND\n   terminals = '16'\nGROUP BY terminals\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Worst TPCC",
   "type": "stat",
   "description": "terminals = 16\n\nclient-time = 60",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n   min(CAST(result->>'throughput' AS DOUBLE PRECISION)) AS \"throughput\"\nFROM test_table\nWHERE\n   $__timeFilter(\"time\") AND\n   benchmark_type = 'tpcc' AND\n   terminals = '16'\nGROUP BY terminals\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Last Smallbank",
   "type": "stat",
   "description": "terminals = 16\n\nclient-time = 60",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n   CAST(result->>'throughput' AS DOUBLE PRECISION) AS \"throughput\"\nFROM test_table\nWHERE\n   $__timeFilter(\"time\") AND\n   benchmark_type = 'smallbank' AND\n   terminals = '16'\n"
    }
   ]
  },
  {
   "title": "Best Smallbank",
   "type": "stat",
   "description": "terminals = 16\n\nclient-time = 60",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n   MAX(CAST(result->>'throughput' AS DOUBLE PRECISION)) AS \"throughput\"\nFROM test_table\nWHERE\n   $__timeFilter(\"time\") AND\n   benchmark_type = 'smallbank' AND\n   terminals = '16'\nGROUP BY terminals\nORDER BY 1"
    }
   ]
  },
  {
   "title": "AVG Smallbank",
   "type": "stat",
   "description": "terminals = 16\n\nclient-time = 60",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n   AVG(CAST(result->>'throughput' AS DOUBLE PRECISION)) AS \"throughput\"\nFROM test_table\nWHERE\n   $__timeFilter(\"time\") AND\n   benchmark_type = 'smallbank' AND\n   terminals = '16'\nGROUP BY terminals\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Worst Smallbank",
   "type": "stat",
   "description": "terminals = 16\n\nclient-time = 60",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n   min(CAST(result->>'throughput' AS DOUBLE PRECISION)) AS \"throughput\"\nFROM test_table\nWHERE\n   $__timeFilter(\"time\") AND\n   benchmark_type = 'smallbank' AND\n   terminals = '16'\nGROUP BY terminals\nORDER BY 1"
    }
   ]
  },
  {
   "title": "TPC-C",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "throughput" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 1\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_table\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'tpcc' AND\n  terminals = '1'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 2\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_table\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'tpcc' AND\n  terminals = '2'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 4\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_table\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'tpcc' AND\n  terminals = '4'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 8\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_table\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'tpcc' AND\n  terminals = '8'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 16\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_table\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'tpcc' AND\n  terminals = '16'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "SmallBank",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "throughput" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 1\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_table\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'smallbank' AND\n  terminals = '1'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 2\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_table\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'smallbank' AND\n  terminals = '2'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 4\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_table\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'smallbank' AND\n  terminals = '4'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 8\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_table\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'smallbank' AND\n  terminals = '8'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 16\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_table\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'smallbank' AND\n  terminals = '16'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Last YCSB",
   "type": "stat",
   "description": "terminals = 16\n\nclient-time = 60",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n   CAST(result->>'throughput' AS DOUBLE PRECISION) AS \"throughput\"\nFROM test_table\nWHERE\n   $__timeFilter(\"time\") AND\n   benchmark_type = 'ycsb' AND\n   terminals = '16'\n"
    }
   ]
  },
  {
   "title": "Best YCSB",
   "type": "stat",
   "description": "terminals = 16\n\nclient-time = 60",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n   MAX(CAST(result->>'throughput' AS DOUBLE PRECISION)) AS \"throughput\"\nFROM test_table\nWHERE\n   $__timeFilter(\"time\") AND\n   benchmark_type = 'ycsb' AND\n   terminals = '16'\nGROUP BY terminals\nORDER BY 1"
    }
   ]
  },
  {
   "title": "AVG YCSB",
   "type": "stat",
   "description": "terminals = 16\n\nclient-time = 60",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n   AVG(CAST(result->>'throughput' AS DOUBLE PRECISION)) AS \"throughput\"\nFROM test_table\nWHERE\n   $__timeFilter(\"time\") AND\n   benchmark_type = 'ycsb' AND\n   terminals = '16'\nGROUP BY terminals\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Worst YCSB",
   "type": "stat",
   "description": "terminals = 16\n\nclient-time = 60",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n   min(CAST(result->>'throughput' AS DOUBLE PRECISION)) AS \"throughput\"\nFROM test_table\nWHERE\n   $__timeFilter(\"time\") AND\n   benchmark_type = 'ycsb' AND\n   terminals = '16'\nGROUP BY terminals\nORDER BY 1"
    }
   ]
  },
  {
   "title": "YCSB",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "throughput" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 1\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_table\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'ycsb' AND\n  terminals = '1'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 2\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_table\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'ycsb' AND\n  terminals = '2'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 4\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_table\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'ycsb' AND\n  terminals = '4'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 8\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_table\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'ycsb' AND\n  terminals = '8'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  result->>'throughput' AS \"terminals = 16\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM test_table\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = 'ycsb' AND\n  terminals = '16'\nORDER BY 1"
    }
   ]
  }
 ]
}