---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: grafana
  labels:
    app: grafana
    env: testing
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: grafana
      env: testing
  template:
    metadata:
      labels:
        app: grafana
        env: testing
    spec:
      nodeSelector:
        env: testing
      containers:
        - name: grafana
          image: "{{ grafana_container_image }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          # TODO: I need to do something about the SECRET_KEY but I'm not sure what
