---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ env }}-timescaledb"
  namespace: performance
  labels:
    app: timescaledb
    env: "{{ env }}"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: timescaledb
      env: "{{ env }}"
  template:
    metadata:
      labels:
        app: timescaledb
        env: "{{ env }}"
    spec:
      nodeSelector:
        env: "{{ env }}"
      volumes:
        - name: timescaledb-volume
      containers:
        - name: timescaledb
          image: "{{ timescaledb_container_image }}"
          imagePullPolicy: "{{ image_pull_policy }}"
          ports:
            - containerPort: 5433
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: TS_TUNE_MEMORY
              value: "8GB"
            - name: TS_TUNE_NUM_CPUS
              value: "4"
          volumeMounts:
            - name: timescaledb-volume
              mountPath: /var/lib/postgresql/data
          volume:
            - name: timescaledb
              persistentVolumeCliam:
                claimName: timescaledb
