---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: performance
  name: timescaledb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi