kind: PersistentVolume
apiVersion: v1
metadata:
  name: timescaledb-pv
  namespace: performance
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/timescaledbPV"