---
kind: Service
apiVersion: v1
metadata:
  name: timescaledb-service
  namespace: performance
spec:
  type: NodePort
  selector:
    app: timescaledb
  ports:
  - protocol: TCP
    port: 5432
    #targetPort: 3000
    nodePort: 33000
  #externalTrafficPolicy: Cluster
