---
kind: Service
apiVersion: v1
metadata:
  name: timescaledb-service
  namespace: performance
  labels:
    app: timescaledb
spec:
  type: NodePort
  selector:
    app: timescaledb
  ports:
  - protocol: TCP
    port: 5432
    nodePort: 30003
  externalTrafficPolicy: Local 