---
kind: Service
apiVersion: v1
metadata:
  name: timescaledb-service
  namespace: performance
spec:
  type: ClusterIP
  selector:
    app: timescaledb
  ports:
  - protocol: TCP
    port: 5432
    #targetPort: 3000
    # nodePort: 30000
  #externalTrafficPolicy: Cluster
