---
kind: Service
apiVersion: v1
metadata:
  name: timescaledb-service
  namespace: "{{ env }}-performance"
  labels:
    app: timescaledb
    env: "{{ env }}"
spec:
  type: NodePort
  selector:
    app: timescaledb
    env: "{{ env }}"
  ports:
  - protocol: TCP
    port: 5432
    nodePort: 32233
