kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  namespace: performance
#   labels:
#     type: local
#     app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/postgresPV"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: performance
  name: timescaledb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: Secret
metadata:
  namespace: performance
  name: timescaledb
type: Opaque
data:
  username: YWRtaW4=
  # username: admin
  password: YWRtaW5wd2Q=
  # password: adminpwd
  database: YWRtaW5kYg==
  # database: admindb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: performance
  name: timescaledb
  labels:
    app: timescaledb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      containers:
      - name: timescaledb
        image: timescale/timescaledb:latest-pg12
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: timescaledb
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: timescaledb
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: timescaledb
              key: database
        - name: TIMESCALEDB_TELEMETRY
          value: "off"
        - name: TS_TUNE_MEMORY
          value: "8GB"
        - name: TS_TUNE_NUM_CPUS
          value: "4"
        ports:
        - containerPort: 5436
        volumeMounts:
        - name: timescaledb
          mountPath: /var/lib/postgresql/data/
      volumes:
      - name: timescaledb
        persistentVolumeClaim:
          claimName: timescaledb
---
apiVersion: v1
kind: Service
metadata:
  namespace: performance
  name: timescaledb
  labels:
    app: timescaledb
spec:
  type: NodePort
  selector:
    app: timescaledb
  ports:
  - protocol: TCP
    port: 5436
    nodePort: 32222
# Trigger