{
 "title": "Monitoring",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Performance Storage Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Performance Storage Service Availability",
   "type": "graph",
   "description": "This tracks whether the Django performance storage service is up or not. This is helpful for tracking SLAs. Alerts will be created if the service goes down.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{env=\"production\",app=\"pss\"}",
     "legendFormat": "{{kubernetes_name}}:{{instance}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Requests / 5m" }
   ],
   "targets": [
    {
     "expr": "sum(rate(django_http_requests_total_by_view_transport_method_total{app=\"pss\",env=\"production\",view!~\"prometheus-django-metrics|healthcheck\"}[5m])*300) by(method, view)\n",
     "legendFormat": "{{view}}:{{method}}"
    }
   ]
  },
  {
   "title": "Error Codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Errors/5m" }
   ],
   "targets": [
    {
     "expr": "increase(django_http_responses_total_by_status_view_method_total{app=\"pss\",env=\"production\",status!~\"2..|404\"}[5m])",
     "legendFormat": "{{view}}:{{status}}"
    }
   ]
  },
  { "title": "Grafana", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "stats.noise.page Service Availability",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{instance=\"https://stats.noise.page\",job=\"blackbox\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "TimescaleDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "TimescaleDB Service Availability",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pg_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Database Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(pg_database_size_bytes) / 107374182400",
     "legendFormat": "Storage used"
    }
   ]
  },
  { "title": "TimescaleDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } }
 ]
}