{
 "title": "Experiments",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "TATP Scalability ",
   "type": "graph",
   "description": "This is the last Benchmark result recorded for TATP in the time range selected.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Throughput (rps)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n   time,\n   CAST(terminals AS TEXT) as metric,\n   CAST(result->>'throughput' AS DOUBLE PRECISION) as value\nFROM test_table\nWHERE\n   $__timeFilter(time) AND\n   benchmark_type = 'tatp'\nGROUP BY time, benchmark_type, terminals, result->>'throughput'\nORDER BY terminals, time"
    }
   ]
  },
  {
   "title": "YCSB - % Change",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT distinct terminals,\n  (FIRST_VALUE(CAST(result->>'throughput' AS DOUBLE PRECISION)) OVER(PARTITION BY terminals order by time desc) -\n  FIRST_VALUE(CAST(result->>'throughput' AS DOUBLE PRECISION)) OVER(PARTITION BY terminals order by time asc)) / \n  FIRST_VALUE(CAST(result->>'throughput' AS DOUBLE PRECISION)) OVER(PARTITION BY terminals order by time desc) * 100 as \"Change\"\n   \nFROM test_table\nWHERE\n   $__timeFilter(time) AND \n   benchmark_type = 'ycsb'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Last YCSB - Worst",
   "type": "stat",
   "description": "terminals = 16\n\nclient-time = 60",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  terminals,\n  result->>'throughput' as \"throughput\"\nFROM test_table\nWHERE\n  id IN (SELECT\n      DISTINCT ON (terminals) id\n    FROM test_table\n    WHERE\n      $__timeFilter(time) AND\n      benchmark_type = 'ycsb'\n    GROUP BY time, terminals, id\n    ORDER BY terminals, time desc) AND\n  $__timeFilter(time) AND\n  benchmark_type = 'ycsb'\nORDER BY result->>'throughput' ASC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Last YCSB - Best",
   "type": "stat",
   "description": "terminals = 16\n\nclient-time = 60",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  terminals,\n  result->>'throughput' as \"throughput\"\nFROM test_table\nWHERE\n  id IN (SELECT\n      DISTINCT ON (terminals) id\n    FROM test_table\n    WHERE\n      $__timeFilter(time) AND\n      benchmark_type = 'ycsb'\n    GROUP BY time, terminals, id\n    ORDER BY terminals, time desc) AND\n  $__timeFilter(time) AND\n  benchmark_type = 'ycsb'\nORDER BY result->>'throughput' DESC\nLIMIT 1"
    }
   ]
  }
 ]
}