---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ env }}-timescaledb"
  namespace: performance
  labels:
    app: timescaledb
    env: "{{ env }}"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: timescaledb
      env: "{{ env }}"
  template:
    metadata:
      labels:
        app: timescaledb
        env: "{{ env }}"
    spec:
      nodeSelector:
        env: "{{ env }}"
      containers:
        - name: timescaledb
          image: "{{ timescaledb_container_image }}"
          imagePullPolicy: "{{ image_pull_policy }}"
          # command: postgres -c logging_collector=on -c log_destination=stderr -c log_directory=/logs
          # command:
          #   - "postgres"
          #   - "-c"
          #   - "max_connections=500"
          # args: ["-c", "max_connections=500"]
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: postgres
          volumeMounts:
            - name: timescaledb-volume
              mountPath: /var/lib/postgresql/data
      # volumes:
      #   - name: timescaledb-volume
          # persistentVolumeClaim:
          #   claimName: timescaledb-pv-claim
