---

- name: create the k8s user
  user: name="{{ k8s_user }}" append=yes state=present createhome=yes shell=/bin/bash

- name: allow the k8s user to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    line: "{{ k8s_user }} ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"