---
- hosts: k8s_master
  name: Deploy Moniotoring Grafana
  vars:
    dir_repo: "{{ inventory_dir | dirname }}"
    dir_deploy: "{{ inventory_dir }}"
    dir_k8s_grafana: "{{ dir_deploy }}/kubernetes/monitoring/grafana"
    service_hostname: incrudibles-k8s.db.pdl.cmu.edu
    ansible_python_interpreter: /usr/bin/python3
  pre_tasks:
    - name: Ensure k8s module dependencies are installed.
      pip:
        name: openshift
        state: present
  tasks:
    - name: Apply Grafana Deployment Configs
      vars:
        config: "{{ dir_k8s_grafana }}/{{ item }}"
      k8s:
        state: present
        definition: "{{ lookup('template', '{{ config }}') }}"
      loop:
        - persistent-volume.yml
        - persistent-volume-claim.yml
        - deployment.yml
        - service.yml