---

- hosts: "{{ host_override | default('k8s_master') }}"
  name: Deploy Prometheus
  vars:
    dir_deployment: "{{ inventory_dir }}"
    dir_k8s_prometheus: "{{ dir_deployment }}/kubernetes/monitoring/prometheus"
  pre_tasks:
    - name: Ensure k8s module dependencies are installed.
      pip:
        state: present
        name: openshift

  tasks:
    - name: Apply Prometheus Deployment Configs
      vars:
        config: "{{ dir_k8s_prometheus }}/{{ item }}"
      community.kubernetes.k8s:
        state: present
        definition: "{{ lookup('template', '{{ config }}') }}"
      loop:
        - cluster-role.yml
        - cluster-role-binding.yml
        - config-map.yml
        - persistent-volume.yml
        - persistent-volume-claim.yml
        - deployment.yml
        - service.yml