---
- hosts: "{{ host_override | default('k8s_master') }}"
  name: Deploy Performance Storage Service
  vars:
    dir_repo: "{{ inventory_dir }}"
    dir_k8s_pss: "{{ dir_repo }}/kubernetes/performance/performance-storage-service"
    service_port_dict:
      local: 30001
      testing: 30001
      staging: 31001
      production: 32001
    service_port: "{{ service_port_dict[env] }}"
  pre_tasks:
    - name: Ensure k8s module dependencies are installed.
      pip:
        name: openshift
        state: present
  tasks:
    - name: Remove Old Migration
      vars:
        job_file: "{{ dir_k8s_pss }}/migration-job.yml"
      k8s:
        state: absent
        definition: "{{ lookup('template', '{{ job_file }}') }}"
    
    # - name: Remove Old Migration Pods #This is experimental
    #   k8s:
    #     state: absent
    #     kind: Pods
    #     namespace: performance
    #     name: django-migrations-*
        
    - name: Migrate Database
      vars:
        job_file: "{{ dir_k8s_pss }}/migration-job.yml"
      k8s:
        state: present
        definition: "{{ lookup('template', '{{ job_file }}') }}"

    - name: Create Performance Storage Service Deployment
      vars:
        deployment_file: "{{ dir_k8s_pss }}/deployment.yml"
      k8s:
        state: present
        definition: "{{ lookup('template', '{{ deployment_file }}') }}"

    - name: Create Performance Service
      vars:
        service_file: "{{ dir_k8s_pss }}/service.yml"
      k8s:
        state: present
        definition: "{{ lookup('template', '{{ service_file }}') }}" # Trigger
