---
- hosts: "{{ host_override | default('k8s_master') }}"
  name: Deploy Performance Storage Service
  vars:
    dir_repo: "{{ inventory_dir }}"
    dir_k8s_pss: "{{ dir_repo }}/kubernetes/performance/performance-storage-service"
  pre_tasks:
    - name: Ensure k8s module dependencies are installed.
      pip:
        name: openshift
        state: present
  tasks:
  - name: Create Performance Storage Service Deployment
    vars:
      deployment_file: "{{ dir_k8s_pss }}/deployment.yml"
    k8s:
      state: present
      definition: "{{ lookup('template', '{{ deployment_file }}') }}"

  - name: Create Performance Service
    vars:
      service_file: "{{ dir_k8s_pss }}/service.yml"
    k8s:
      state: present
      definition: "{{ lookup('template', '{{ service_file }}') }}"
