---
- hosts: k8s_master
  name: Deploy Performance Storage Service
  vars:
    dir_repo: "{{ inventory_dir }}"
    dir_k8s: "{{ dir_repo }}/kubernetes/performance"
    dir_k8s_deployment: "{{ dir_k8s }}/performance-storage-service/deployment"
  pre_tasks:
    - name: Ensure k8s module dependencies are installed.
      pip:
        name: openshift
        state: present
  tasks:
  - name: Create Performance Storage Service Deployment
    vars:
      deployment_file: "{{ dir_k8s_deployment }}/{{ env }}/deployment.yml"
    k8s:
      state: present
      definition: "{{ lookup('template', '{{ deployment_file }}') | from_yaml }}"

  - name: Create Performance Service
    k8s:
      state: present
      src: "{{ dir_k8s }}/service.yml"
