---

- hosts: "{{ host_override | default('k8s_master') }}"
  name: Deploy TimescaleDB
  vars:
    dir_repo: "{{ inventory_dir }}"
    dir_k8s_timescaledb: "{{ dir_repo }}/kubernetes/performance/timescaledb"
    service_port_dict:
      testing: 30003
      staging: 31003
      production: 32003
    service_port: "{{ service_port_dict[env] }}"
  pre_tasks:
    - name: Ensure k8s module dependencies are installed.
      pip:
        state: present
        name: openshift

    - name: Ensure psycopg2 is installed
      pip:
        state: present
        name: psycopg2-binary

  tasks:
    - name: Create TimescaleDB Deployment
      vars:
        deployment_file: "{{ dir_k8s_timescaledb }}/deployment.yml"
      k8s:
        state: present
        definition: "{{ lookup('template', '{{ deployment_file }}') }}"

    - name: Create TimescaleDB Service
      vars:
        service_file: "{{ dir_k8s_timescaledb }}/service.yml"
      k8s:
        state: present
        definition: "{{ lookup('template', '{{ service_file }}') }}"

    - name: Wait for postgres to start
      register: result
      postgresql_ping:
        state: present
        ssl_mode: disable
        db: postgres
        login_host: "incrudibles-testing.db.pdl.cmu.edu"
        port: 30003
        login_user: "{{ pss_db_user }}"
        login_password: "{{ pss_db_password }}"
      # until: result.is_available == True
      # retries: 10
      # delay: 10
    - name: Print SSH public key
      debug: var=result

    - name: Add pss_datatabase Database
      postgresql_db:
        state: present
        name: "{{ pss_db_name }}"
        login_host: "incrudibles-testing.db.pdl.cmu.edu"
        port: 30003
        login_user: "{{ pss_db_user }}"
        login_password: "{{ pss_db_password }}"