---

- hosts: "{{ host_override | default('k8s_master') }}"
  name: Deploy TimescaleDB
  vars:
    dir_repo: "{{ inventory_dir }}"
    dir_k8s_timescaledb: "{{ dir_repo }}/kubernetes/performance/timescaledb"
    service_port_dict:
      testing: 30003
      staging: 31003
      production: 32003
    service_port: "{{ service_port_dict[env] }}"
  pre_tasks:
    - name: Ensure k8s module dependencies are installed.
      pip:
        name: openshift
        state: present
  tasks:
    - name: Create TimescaleDB Deployment
      vars:
        deployment_file: "{{ dir_k8s_timescaledb }}/deployment.yml"
      k8s:
        state: present
        definition: "{{ lookup('template', '{{ deployment_file }}') }}"

    - name: Create TimescaleDB Service
      vars:
        service_file: "{{ dir_k8s_timescaledb }}/service.yml"
      k8s:
        state: present
        definition: "{{ lookup('template', '{{ service_file }}') }}"