- hosts: localhost
  tasks:
  - name: Create a Deployment by reading the definition from a local file
    k8s:
      state: present
      src: ../../kubernetes/performance/performance-storage-service/local/deployment.yml

  - name: Create a Service object by reading the definition from a file
    k8s:
      state: present
      src: ../../kubernetes/performance/service.yml
