- hosts: "{{host_name}}"
  tasks:
  - name: Create Performance Storage Service Deployment
    k8s:
      state: present
      src: ../../kubernetes/performance/performance-storage-service/local/deployment.yml

  - name: Create Performance Service
    k8s:
      state: present
      src: ../../kubernetes/performance/service.yml
