---
- name: Add grafana data source
  grafana_datasource:
    name: "noisepage-db"
    grafana_url: "http://incrudibles-testing.db.pdl.cmu.edu/grafana"
    url_username: "admin"
    url_password: "admin"
    ds_type: "postgres"
    ds_url: "incrudibles-testing.db.pdl.cmu.edu:30003"
    database: "test_db"
    # user: "{{ pss_db_user }}"
    user: "postgres"
    # password: "{{ pss_db_password }}"
    password: "password"
    sslmode: "disable"