---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ env }}-grafana"
  namespace: "performance"
  labels:
    app: grafana
    env: "{{ env }}"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: grafana
      env: "{{ env }}"
  template:
    metadata:
      labels:
        app: grafana
        env: "{{ env }}"
    spec:
      nodeSelector:
        env: "{{ env }}"
      volumes:
        - name: grafana-volume
      containers:
        - name: grafana
          image: "{{ grafana_container_image }}"
          imagePullPolicy: "{{ image_pull_policy }}"
          ports:
            - name: http
              containerPort: 3000
          volumeMounts:
            - name: grafana-volume
              mountPath: /var/lib/grafana
          env:
            GF_server_serve_from_sub_path: "true"
            # - name: GF_PATHS_LOGS
            #   value: /var/log/grafana/
            # - name: GF_LOG_MODE
            #   value: "console file"
            # - name: GF_SERVER_DOMAIN
            #   value: "incrudibles-testing.db.pdl.cmu.edu"
            # - name: GF_SERVER_ROOT_URL
            #   value: "%(protocol)s://%(domain)s/grafana"
            # - name: GF_server_serve_from_sub_path
            #   value: "true"
