---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ env }}-grafana"
  namespace: "performance"
  labels:
    app: grafana
    env: "{{ env }}"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: grafana
      env: "{{ env }}"
  template:
    metadata:
      labels:
        app: grafana
        env: "{{ env }}"
    spec:
      nodeSelector:
        env: "{{ env }}"
      volumes:
        - name: grafana-volume
      containers:
        - name: grafana
          image: "{{ grafana_container_image }}"
          imagePullPolicy: "{{ image_pull_policy }}"
          ports:
            - name: http
              containerPort: 3000
          volumeMounts:
            - name: grafana-volume
              mountPath: /var/lib/grafana
          env:
            - name: GF_PATHS_LOGS
              value: /var/log/grafana/
            - name: GF_LOG_MODE
              value: "console file"
            - name: GF_ROOT_URL
              value: "http://incrudibles-testing.db.pdl.cmu.edu:30002"
