---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: "{{ env }}-performance"
  labels:
    app: grafana
    env: "{{ env }}"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: grafana
      env: "{{ env }}"
  template:
    metadata:
      labels:
        app: grafana
        env: "{{ env }}"
    spec:
      nodeSelector:
        env: "{{ env }}"
      containers:
        - name: grafana
          image: "{{ grafana_container_image }}"
          imagePullPolicy: "{{ image_pull_policy }}"
          ports:
            - name: http
              containerPort: 3000
