kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: performance
  name: grafana-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi