---
kind: Service
apiVersion: v1
metadata:
  name: grafana-service
  namespace: "{{ env }}-performance"
  labels:
    app: grafana
    env: "{{ env }}"
spec:
  type: NodePort
  selector:
    app: grafana
    env: "{{ env }}"
  ports:
  - protocol: TCP
    port: 3000
    nodePort: 32000
