---
kind: Service
apiVersion: v1
metadata:
  name: grafana-service
  namespace: grafana
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 32000
  #TODO nodeport information is missing in our deployment view 
  externalTrafficPolicy: Cluster
