{
 "title": "OLTPBench",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Type",
    "query": "SELECT benchmark_type FROM oltpbench_results;"
   },
   {
    "name": "Terminals",
    "query": "SELECT terminals FROM oltpbench_results;"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n   AVG(CAST(metrics->>'throughput' AS DOUBLE PRECISION)) AS \"throughput\"\nFROM oltpbench_results\nWHERE\n   $__timeFilter(\"time\") AND\n   benchmark_type = '$Type' AND\n   terminals = '$Terminals'\nGROUP BY terminals"
    }
   ]
  },
  {
   "title": "$Type- % Change",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT distinct terminals,\n  (FIRST_VALUE(CAST(metrics->>'throughput' AS DOUBLE PRECISION)) OVER(PARTITION BY terminals order by time desc) -\n  FIRST_VALUE(CAST(metrics->>'throughput' AS DOUBLE PRECISION)) OVER(PARTITION BY terminals order by time asc)) / \n  FIRST_VALUE(CAST(metrics->>'throughput' AS DOUBLE PRECISION)) OVER(PARTITION BY terminals order by time desc) * 100 as \"Change\"\n   \nFROM oltpbench_results\nWHERE\n   $__timeFilter(time) AND \n   benchmark_type = '$Type'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "$Type",
   "type": "graph",
   "gridPos": { "h": 18, "w": 13, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "throughput" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  metrics->>'throughput' AS \"terminals = 1\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = '$Type' AND\n  terminals = '1'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  metrics->>'throughput' AS \"terminals = 2\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = '$Type' AND\n  terminals = '2'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  metrics->>'throughput' AS \"terminals = 4\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = '$Type' AND\n  terminals = '4'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  metrics->>'throughput' AS \"terminals = 8\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = '$Type' AND\n  terminals = '8'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  metrics->>'throughput' AS \"terminals = 16\",\n  \"git_commit_id\" AS \"git_commit_id\"\nFROM oltpbench_results\nWHERE\n  $__timeFilter(\"time\") AND\n  benchmark_type = '$Type' AND\n  terminals = '16'\nORDER BY 1"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 11, "x": 0, "y": 6 },
   "content": "# Highest $Type, terminals = $Terminals"
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  metrics->>'throughput'\nFROM oltpbench_results\nWHERE\n  id IN (SELECT id\n          FROM oltpbench_results\n          WHERE $__timeFilter(time) AND\n                benchmark_type = '$Type' AND\n                terminals = '$Terminals'\n          GROUP BY time, terminals, id\n          ORDER BY terminals, time desc) AND\n  $__timeFilter(time)\nORDER BY metrics->>'throughput' DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Commit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,git_commit_id\nFROM oltpbench_results\nWHERE\n  id IN (SELECT id\n          FROM oltpbench_results\n          WHERE $__timeFilter(time) AND\n                benchmark_type = '$Type' AND\n                terminals = '$Terminals'\n          GROUP BY time, terminals, id\n          ORDER BY terminals, time desc) AND\n  $__timeFilter(time)\nORDER BY metrics->>'throughput' DESC\nLIMIT 1"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 11, "x": 0, "y": 12 },
   "content": "# Lowest $Type, terminals = $Terminals"
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  metrics->>'throughput'\nFROM oltpbench_results\nWHERE\n  id IN (SELECT id\n          FROM oltpbench_results\n          WHERE $__timeFilter(time) AND\n                benchmark_type = '$Type' AND\n                terminals = '$Terminals'\n          GROUP BY time, terminals, id\n          ORDER BY terminals, time desc) AND\n  $__timeFilter(time)\nORDER BY metrics->>'throughput' ASC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Commit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,git_commit_id\nFROM oltpbench_results\nWHERE\n  id IN (SELECT id\n          FROM oltpbench_results\n          WHERE $__timeFilter(time) AND\n                benchmark_type = '$Type' AND\n                terminals = '$Terminals'\n          GROUP BY time, terminals, id\n          ORDER BY terminals, time desc) AND\n  $__timeFilter(time)\nORDER BY metrics->>'throughput' ASC\nLIMIT 1"
    }
   ]
  }
 ]
}