---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      nodeSelector:
        env: master
      volumes:
        - name: grafana-volume
          persistentVolumeClaim:
            claimName: monitoring-grafana-pv-claim
      containers:
        - name: grafana
          image: "{{ grafana_container_image }}"
          imagePullPolicy: "{{ image_pull_policy }}"
          ports:
            - name: http
              containerPort: 3000
          volumeMounts:
            - name: grafana-volume
              mountPath: /var/lib/grafana
          env:
            - name: GF_PATHS_LOGS
              value: /var/log/grafana/
            - name: GF_LOG_MODE
              value: "console file"
            - name: GF_SERVER_DOMAIN
              value: "{{ service_hostname }}"
            - name: GF_SERVER_ROOT_URL
              value: "https://{{ service_hostname }}/grafana"
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: "true"
            - name: GF_SERVER_HTTP_PORT
              value: "3000"
            - name: GF_AUTH_GITHUB_ENABLED
              value: "true"
            - name: GF_AUTH_GITHUB_ALLOW_SIGN_UP
              value: "true"
            - name: GF_AUTH_GITHUB_ALLOWED_ORGANIZATIONS
              value: "cmu-db"
            - name: GF_SECURITY_ADMIN_USER
              value: "admin"
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets-k8s-master
                  key: gf_admin_password
            #GitHub Login
            - name: GF_AUTH_GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: secrets-k8s-master
                  key: gf_auth_github_client_id
            - name: GF_AUTH_GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets-k8s-master
                  key: gf_auth_github_client_secret