---

kind: Service
apiVersion: v1
metadata:
  name: grafana-service
  namespace: performance
  labels:
    app: grafana
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
  - protocol: TCP
    port: 3000
    nodePort: 32004
  externalTrafficPolicy: Local